examples/readline/README.en.md, examples/readline/README.md, examples/readline/index.js
This pull request includes updates to the `examples/readline` directory, improving documentation and code organization. The changes focus on enhancing the README files and refactoring the main JavaScript file for better clarity.
Documentation improvements:
* [`examples/readline/README.en.md`](diffhunk://#diff-d6c3ba97bf50d2809e3db8ec29bed1168f89a9248e88cde4c31f2f075f7a2109R1-R28): Added a new English README file explaining how to run the example and process terminal input using Node.js's `readline` module.
* [`examples/readline/README.md`](diffhunk://#diff-f1ff00742f528b4bab05d281fea19836d15d88fc8beebee7b0f7771ab2b049e2R1-R28): Updated the Korean README file to match the structure and content of the new English README file.
Code refactoring:
* …
=> refactor(examples-readline): update documentation

examples/readline/README.en.md, examples/readline/README.md, examples/solutions-readline/README.en.md, examples/solutions-readline/README.md, examples/solutions-readline/src/1000.js, examples/solutions-readline/src/1001.js, examples/solutions-readline/src/29751.js, examples/solutions-readline/templates/index.js
This pull request includes several updates to the `examples/readline` and `examples/solutions-readline` directories. The changes focus on improving documentation, adding new examples, and restructuring code for better readability and maintainability.
* `examples/readline/README.en.md` and `examples/readline/README.md`: Updated the command to start the examples from `npm start` to `npm run start`. [[1]](diffhunk://#diff-d6c3ba97bf50d2809e3db8ec29bed1168f89a9248e88cde4c31f2f075f7a2109L25-R25) [[2]](diffhunk://#diff-f1ff00742f528b4bab05d281fea19836d15d88fc8beebee7b0f7771ab2b049e2L25-R25)
* `examples/solutions-readline/README.en.md` and `examples/solutions-readline/README.md`: Added new README files to provide detailed instructions on running the examples and information about the …
=> refactor(examples-solutions-readline): update documentation

packages/bananass-utils-console/package.json, packages/bananass-utils-console/src/index.js, packages/bananass-utils-console/src/logger.js, packages/bananass/src/cli.js, packages/bananass/src/commands/bananass-build/webpack.js
This pull request introduces a new logger utility and integrates it into the existing `bananass` package. The most important changes include adding the logger utility, updating the `package.json` to export the logger, and modifying several files to use the new logger.
Logger utility integration:
* [`packages/bananass-utils-console/src/logger.js`](diffhunk://#diff-ca61110b96c84d07f62507411be0440c90521177060be76fd4fddcaeb122cd33R1-R127): Added a new logger utility with methods for logging and debugging messages.
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eR7): Updated the exports to include the new logger utility.
* [`packages/bananass-utils-console/src/index.js`](diffhunk://#diff-6fe2564e60a8ff56b34df5b2 …
=> feat: create `logger.js` and add debug and quiet mode

packages/bananass/src/commands/bananass-build/webpack.js
This pull request includes changes to the `packages/bananass/src/commands/bananass-build/webpack.js` file to improve the handling of the output directory cleaning process during the build.
Improvements to output directory cleaning:
* Added `rmSync` from `node:fs` to manually clean the output directory before emitting files.
* Commented out the `webpackConfigs.output.clean` option to avoid using it, as it could result in only one file in the output directory.
* Implemented a manual cleaning process using `rmSync` to prevent race conditions and ensure the output directory is cleaned only once.
=> fix(bananass-build): correct `clean` option behavior

.github/sync-client.yml, .vscode/extensions.json
This pull request includes changes to configuration files to update the destination paths and add new recommended extensions for VSCode. The most important changes include modifying the destination path for VSCode extensions and adding a new extension recommendation.
Configuration updates:
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1L42-R42): Changed the destination path for the VSCode extensions file from `./configs/.vscode/npm-extensions.json` to `./configs/.vscode/web-extensions.json`.
VSCode extensions:
* [`.vscode/extensions.json`](diffhunk://#diff-c16655a98a3ee89a7636a59c59a72b0e93649e3a1e947327cfc43a1336b4e912R4): Added `stylelint.vscode-stylelint` to the list of recommended extensions.
=> chore: update `.vscode/extensions.json`

examples/solutions-bananass/bananass/1000.js, examples/solutions-bananass/bananass/1001.js, examples/solutions-bananass/bananass/29751.js, examples/solutions-bananass/package.json, package-lock.json, package.json
This pull request includes several changes to the `examples/solutions-bananass` project, primarily focused on refactoring functions and updating dependencies. The most important changes are listed below:
* [`examples/solutions-bananass/bananass/1000.js`](diffhunk://#diff-cee990384708d6ee19026603ffb858de9ae8dc486da42ebb853c297bb946ac87L3-R12): Refactored the function to use a named `solution` function instead of an anonymous function and updated the export statement.
* [`examples/solutions-bananass/bananass/1001.js`](diffhunk://#diff-9462768f82f8319792e64b734fd98823ce8baf518674d12639966ae6f6f01008L3-R12): Refactored the function to use a named `solution` function instead of an anonymous function and updated the export statement.
* …
=> refactor(examples-solutions-bananass): refactor functions and update dependency

.prettierrc.js, package-lock.json, package.json, packages/prettier-config-bananass/package.json, packages/prettier-config-bananass/src/index.js, packages/prettier-config-bananass/src/index.test.js
This pull request includes the creation and integration of a new Prettier configuration package named `prettier-config-bananass`. The main changes involve updating configuration files, adding dependencies, and creating the new package with its associated files and tests.
* [`.prettierrc.js`](diffhunk://#diff-7312296367dd7c725b9beb500d7dab7bbeeb2aa03a1010a3fb2935f826d03fa6L1-R1): Changed to use the new `prettier-config-bananass` package.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3-R4): Added `prettier-config-bananass` as a dependency and updated metadata. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3-R4) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d51 …
=> feat(prettier-config-bananass): introduce `prettier-config-bananass` package

package-lock.json, packages/eslint-config-bananass-react/package.json, packages/eslint-config-bananass-react/src/configs/recommended.js, packages/eslint-config-bananass-react/src/rules/react-compiler.js, packages/eslint-config-bananass-react/src/rules/react-hooks.js, packages/eslint-config-bananass-react/src/rules/react.js
This pull request includes updates to the `eslint-config-bananass-react` package to enhance compatibility with React and improve rule enforcement. The most important changes include updating peer dependencies, adding new plugins, and modifying rule configurations.
* [`packages/eslint-config-bananass-react/package.json`](diffhunk://#diff-263baf2bd4636e9041e07fa4d170bdde1545c6a48947ab5ff1f511e289d53356L43-R47): Updated the `react` peer dependency version and added `eslint-plugin-react` to dependencies.
* [`packages/eslint-config-bananass-react/src/configs/recommended.js`](diffhunk://#diff-37166b4a0f48af8c6aba54acd189965704d2f4961b2e15df8c5bc628e1a258a3R16-R20): Added `eslint-plugin-react` and its rules to the recommended configuration. …
=> feat(eslint-config-bananass-react): add `eslint-plugin-react`

package-lock.json, website/eslint-config-bananass-react/config.js, website/eslint-config-bananass-react/package.json
This pull request introduces a new ESLint configuration package specifically for React projects and updates the existing ESLint configuration package. The most important changes include adding the new configuration file, creating the package definition for the new configuration, and updating the script order in the existing package.
New ESLint configuration for React projects:
* [`website/eslint-config-bananass-react/config.js`](diffhunk://#diff-7597fedd6ccb6830cf430ccbbdc5671a2fc7dbb7a674eb5dfd19a0e3eba5970eR1-R3): Added a new configuration file that imports the recommended settings from `eslint-config-bananass-react`.
* [`website/eslint-config-bananass-react/package.json`](diffhunk://#diff-2ad28decc0feb56bf4fa36b29e2b391ff95e8d49cb85f818483d9a594473ba2fR1-R13): Created a new package …
=> feat(website-eslint-config-bananass-react): introduce `website-eslint-config-bananass-react`

packages/bananass-utils-console/package.json, packages/bananass-utils/package.json, packages/bananass/package.json, packages/eslint-config-bananass-react/package.json, packages/eslint-config-bananass/package.json, packages/prettier-config-bananass/package.json
This pull request includes updates to the `homepage` field in the `package.json` files across multiple packages to reflect the new URL for the project's homepage.
Updates to `homepage` field:
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eL59-R59): Updated `homepage` to "https://bananass.lumir.page".
* [`packages/bananass-utils/package.json`](diffhunk://#diff-d163ef114bef61820f7f4b4d32b3deb5f15dfc2b5375c030716132c1b4c31c88L31-R31): Updated `homepage` to "https://bananass.lumir.page".
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432L31-R31): Updated `homepage` to "https://bananass.lumir.page".
* …
=> chore: update homepage URL in `package.json` files to new site

.github/workflows/pull-request.yml, .github/workflows/sync-client.yml
This pull request includes updates to the GitHub Actions workflows to improve concurrency handling and formatting of commit messages and pull request bodies.
Improvements to concurrency handling:
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L8-R8): Updated the `group` key in the `concurrency` section to use the pull request number instead of the reference, ensuring unique groups for each pull request.
Formatting updates:
* [`.github/workflows/sync-client.yml`](diffhunk://#diff-254f50149bdf646bb0bb19197c9fa73d054fdb550909072ed57e0b5bcc39a197L25-R26): Modified the `COMMIT_PREFIX` to use a more descriptive format and updated the `PR_BODY` to improve readability and include an emoji.
=> ci(*): update `pull-request.yml` concurrency group and update `sync-client.yml`

package-lock.json, packages/bananass/package.json, packages/bananass/src/commands/bananass-build/webpack.js, packages/bananass/src/core/structs/config-object-build-options/config-object-build-options.js, packages/bananass/src/core/structs/config-object-build-options/index.js, packages/bananass/src/core/structs/index.js, packages/bananass/src/core/structs/problems/index.js, packages/bananass/src/core/structs/problems/problems.js, packages/bananass/src/core/structs/problems/problems.test.js, packages/bananass/src/core/types.js
This pull request introduces several changes to the `bananass` package to enhance type safety and improve error handling. The most significant changes include adding new dependencies, defining new type structures, and updating the existing code to utilize these new structures.
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432R57-R59): Added `consola` and `superstruct` as new dependencies.
* [`packages/bananass/src/core/structs/config-object-build-options/config-object-build-options.js`](diffhunk://#diff-28f3f916317189e098bbc1c05dde6eb7cdcf3361ac293dd4e798c3d919cba631R1-R42): Defined the `ConfigObjectBuildOptions` type struct using `superstruct` to enforce the structure of build options.
* …
=> feat(bananass): support runtime type validation using `superstruct`

packages/bananass-utils-console/package.json, packages/bananass-utils-vitepress/package.json, packages/bananass/package.json, packages/eslint-config-bananass-react/package.json, packages/eslint-config-bananass/package.json, packages/prettier-config-bananass/package.json
This pull request includes changes to multiple `package.json` files across different packages to add a `publishConfig` section with `provenance` set to true. This ensures that the published packages will have provenance information.
The most important changes include:
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eR67-R69): Added `publishConfig` with `provenance` set to true.
* [`packages/bananass-utils-vitepress/package.json`](diffhunk://#diff-e9935f58a17308158af0563ed80b22f02cba32b411c4e1bd2e2acb76593734a9R75-R77): Added `publishConfig` with `provenance` set to true.
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432R69-R71): Added …
=> chore(*): add `publishConfig` with `provenance` set to `true` in `package.json` files

packages/bananass/src/commands/bananass-bug/bug.js, packages/bananass/src/commands/bananass-build/build.js, packages/bananass/src/commands/bananass-discussion/discussion.js, packages/bananass/src/commands/bananass-home/home.js, packages/bananass/src/commands/bananass-open/open.js, packages/bananass/src/commands/bananass-repo/repo.js, packages/bananass/src/commands/bananass-run/run.js
This pull request includes several changes to the `bananass` package, focusing on improving error handling, cleaning up code, and ensuring consistent logging across different command files. The most important changes include removing unnecessary parameters from the `createSpinner` function, improving error messages, and adding exit logging. Below are the key changes grouped by theme:
* Improved error messages in `bananass-bug`, `bananass-build`, `bananass-discussion`, `bananass-home`, `bananass-open`, `bananass-repo`, and `bananass-run` commands to provide more detailed feedback. [[1]](diffhunk://#diff-c49c2ac0f48f162fb6dd63de6eaaf35f7fc82f0372fc582a3332539634eb576bL71-R81) [[2]](diffhunk://#diff-5b3f690c580caae1e82d3789dd6e78d9b694ac24acc51e672b297b524521fda4L163-L185) …
=> refactor(bananass): remove spinner color configuration and improve error logging

packages/bananass/src/core/structs/solution/solution.js, packages/bananass/src/core/structs/testcase/testcase.js, packages/bananass/src/core/types.js
This pull request includes changes to the `packages/bananass` module to refine the structure and typing of solutions and test cases. The most important changes include modifying the `Solution` function validation, updating the `Testcase` structure, and reorganizing type definitions.
Refinements to structure and typing:
* [`packages/bananass/src/core/structs/solution/solution.js`](diffhunk://#diff-1a3d3e2df9dacfb36c9df0d999baf3a817992c8dce1e5b0f5c753b174312f1aeL30-R32): Modified the `Solution` function validation to accept functions with zero or one parameter.
* [`packages/bananass/src/core/structs/testcase/testcase.js`](diffhunk://#diff-2fae1502d373d29acefcff8a8a39a93c2cc5ca1950b90df60ac300f7c2c117deL9-R9): Added `optional` to the `superstruct` import and updated the `Testcase` structure …
=> fix(bananass): update `Solution` and `Testcase` types to allow optional input parameters

package-lock.json, packages/bananass/package.json, packages/bananass/src/commands/bananass-bug/bug.js, packages/bananass/src/commands/bananass-bug/bug.test.js, packages/bananass/src/commands/bananass-build/build.js, packages/bananass/src/commands/bananass-discussion/discussion.js, packages/bananass/src/commands/bananass-discussion/discussion.test.js, packages/bananass/src/commands/bananass-home/home.js, packages/bananass/src/commands/bananass-home/home.test.js, packages/bananass/src/commands/bananass-info/info.js, packages/bananass/src/commands/bananass-info/info.test.js, packages/bananass/src/commands/bananass-open/open.js, packages/bananass/src/commands/bananass-open/open.test.js, packages/bananass/src/commands/bananass-repo/repo.js, packages/bananass/src/commands/bananass-repo/repo.test.js, packages/bananass/src/commands/bananass-run/run.js, packages/bananass/src/core/structs/config-object/config-object.test.js
This pull request includes multiple changes to the `packages/bananass` directory, focusing on updating package dependencies, adding default configuration objects, and enhancing test coverage for various commands. The most important changes are summarized below:
* Updated the `node` engine requirement in `package.json` to support versions `^20.18.0` and `>= 22.3.0`.
* Added `defaultConfigObject` (`dco`) as a default parameter in several command files (`bug.js`, `build.js`, `discussion.js`, `home.js`, `info.js`). This ensures default values are used when no arguments are provided. [[1]](diffhunk://#diff-c49c2ac0f48f162fb6dd63de6eaaf35f7fc82f0372fc582a3332539634eb576bR14) [[2]](diffhunk://#diff-c49c2ac0f48f162fb6dd63de6eaaf35f7fc82f0372fc582a3332539634eb576bL35-R36) …
=> test(bananass): add default values and tests for `commands` 

eslint.config.mjs, websites/eslint-config-bananass/config.js
This pull request includes updates to the ESLint configuration files to improve type safety by adding type annotations.
Improvements to type safety:
* [`eslint.config.mjs`](diffhunk://#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2R3): Added type annotation for the ESLint configuration array.
* [`websites/eslint-config-bananass/config.js`](diffhunk://#diff-c1f34d5ca272776f85e487187fcf6795c3f6a9a7993cf71e9763e2ece5debefeR3): Added type annotation for the ESLint configuration array.
=> chore(*): add TypeScript type annotations to ESLint configuration files

examples/solutions-bananass-cjs/bananass/2558/index.js, examples/solutions-bananass-cjs/bananass/2558/solution.js, examples/solutions-bananass-cjs/bananass/2558/testcases.js, examples/solutions-bananass-cts/bananass/2558/index.ts, examples/solutions-bananass-cts/bananass/2558/solution.ts, examples/solutions-bananass-cts/bananass/2558/testcases.ts, examples/solutions-bananass-cts/tsconfig.json, examples/solutions-bananass-mjs/bananass/2558/index.js, examples/solutions-bananass-mjs/bananass/2558/solution.js, examples/solutions-bananass-mjs/bananass/2558/testcases.js, examples/solutions-bananass-mts/bananass/2558/index.ts, examples/solutions-bananass-mts/bananass/2558/solution.ts, examples/solutions-bananass-mts/bananass/2558/testcases.ts, examples/solutions-bananass-mts/tsconfig.json, packages/bananass/src/core/types.js, packages/create-bananass/templates/typescript/tsconfig.json
This pull request includes changes to add solutions and test cases for problem 2558 in various module formats (CommonJS, ESM, and TypeScript) and updates to TypeScript configuration files.
* [`examples/solutions-bananass-cjs/bananass/2558/index.js`](diffhunk://#diff-9a30214b1b83072a9f026b547c622ed27163da85dfd33242510fd517e5adf904R1-R4): Added module exports for `solution` and `testcases` in CommonJS format.
* [`examples/solutions-bananass-cjs/bananass/2558/solution.js`](diffhunk://#diff-2341ef73b220bd597d3a6700900183ada745b4ced9359a3801c014b962163e7cR1-R7): Implemented the solution function to sum two numbers from input.
* [`examples/solutions-bananass-cjs/bananass/2558/testcases.js`](diffhunk://#diff-9b74cf966eeb9f2908b371e8abff4056efe505054f942a7221900f9642942dbdR1-R10): Added test …
=> chore(*): add problem number `2558` to the examples

.github/sync-client.yml, packages/eslint-config-bananass/package.json, packages/eslint-config-bananass/src/configs/js.js, packages/eslint-config-bananass/src/configs/jsx-next.js, packages/eslint-config-bananass/src/configs/jsx-react.js, packages/eslint-config-bananass/src/configs/ts.js, packages/eslint-config-bananass/src/configs/tsx-next.js, packages/eslint-config-bananass/src/configs/tsx-react.js, packages/eslint-config-bananass/src/index.js, packages/eslint-config-bananass/src/language-options.js, packages/eslint-config-bananass/tsconfig.json, websites/eslint-config-bananass/config.js
This pull request includes several changes to the `eslint-config-bananass` package to improve TypeScript support and add type annotations. The most important changes include adding TypeScript configuration, updating build scripts, and adding type annotations to various configuration files.
* Added `tsconfig.json` to configure TypeScript compilation for the package. This includes settings for allowing JavaScript files, generating declaration files, and specifying the output directory (`build`).
* Updated `package.json` to include type definitions in the build output and added `typesVersions` to specify the location of type definitions. The build script was also updated to run TypeScript compilation before copying license and README files. …
=> feat(eslint-config-bananass)!: add type support and rename configs

.github/sync-client.yml, .prettierrc.cjs, packages/prettier-config-bananass/package.json, packages/prettier-config-bananass/src/index.js, packages/prettier-config-bananass/src/index.test.js, prettier.config.mjs
This pull request includes several changes to the configuration and module system for the `prettier-config-bananass` package, as well as updates to the `.github/sync-client.yml` file. The most important changes involve the conversion of the package to use ES modules, the addition of a new Prettier configuration file, and the removal of redundant configuration files.
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1L63-L64): Added new Prettier configuration file `prettier.config.mjs` and removed redundant `.prettierrc.cjs` configuration file. [[1]](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1L63-L64) [[2]](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1R77-R78 …
=> refactor(prettier-config-bananass)!: migrate to ESM

.github/sync-client.yml, CONTRIBUTING.en.md, CONTRIBUTING.md, eslint.config.mjs, package-lock.json, package.json, websites/vitepress/en/apis/eslint-config-bananass/references.md, websites/vitepress/en/apis/index.md, websites/vitepress/en/get-started/installation.md, websites/vitepress/en/get-started/quick-start.md, websites/vitepress/en/learn/how-to-parse-input-value.md, websites/vitepress/en/learn/how-to-run-solution-files.md, websites/vitepress/en/learn/index.md, websites/vitepress/en/learn/project-structure.md, websites/vitepress/en/learn/q-and-a.md, websites/vitepress/en/learn/solving-problems-without-bananass-framework.md, websites/vitepress/ko/apis/eslint-config-bananass/index.md, websites/vitepress/ko/apis/eslint-config-bananass/references.md, websites/vitepress/ko/apis/index.md, websites/vitepress/ko/get-started/before-getting-started.md, websites/vitepress/ko/learn/how-to-parse-input-value.md, websites/vitepress/ko/learn/project-structure.md
This pull request introduces several updates to improve documentation, enhance ESLint configurations, and refine project structure. Key changes include expanding contribution guidelines, adding heading IDs to markdown files, and updating ESLint rules for better code quality.
* Expanded `CONTRIBUTING.en.md` with detailed contribution guidelines, including project structure, commit message conventions, and steps for getting started.
* Updated `CONTRIBUTING.md` in Korean to align with the English version, including additional details about supported problem-solving platforms and project structure. [[1]](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L7-R9) [[2]](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L30-R33)
* Added …
=> docs(*): update eslint config and translate `CONTRIBUTING.en.md`

package-lock.json, packages/bananass/package.json, websites/vitepress/ko/learn/q-and-a.md
This pull request includes a minor dependency update in the `packages/bananass/package.json` file. The `open` package has been updated from version `^10.1.1` to `^10.1.2` to ensure compatibility or include bug fixes.
=> chore(deps): bump `open` from `v10.1.1` to `v10.1.2`

examples/solutions-bananass-cjs/bananass/2420.js, examples/solutions-bananass-cts/bananass/2420.ts, examples/solutions-bananass-mjs/bananass/2420.js, examples/solutions-bananass-mts/bananass/2420.ts, websites/vitepress/en/solutions/baekjoon/1000.md, websites/vitepress/en/solutions/baekjoon/1001.md, websites/vitepress/en/solutions/baekjoon/2420.md, websites/vitepress/en/solutions/baekjoon/2558.md, websites/vitepress/en/solutions/baekjoon/29751.md, websites/vitepress/en/solutions/baekjoon/31403.md, websites/vitepress/ko/solutions/baekjoon/1000.md, websites/vitepress/ko/solutions/baekjoon/1001.md, websites/vitepress/ko/solutions/baekjoon/2420.md, websites/vitepress/ko/solutions/baekjoon/2558.md, websites/vitepress/ko/solutions/baekjoon/29751.md, websites/vitepress/ko/solutions/baekjoon/31403.md
This pull request introduces new solutions for several Baekjoon problems in both JavaScript and TypeScript across different module formats (CJS, MJS, CTS, MTS). It also updates the corresponding documentation in English and Korean to include these solutions. Below is a summary of the most important changes:
* Added solutions for problem 2420 ("Make a Difference") in `examples/solutions-bananass-cjs/bananass/2420.js`, `examples/solutions-bananass-cts/bananass/2420.ts`, `examples/solutions-bananass-mjs/bananass/2420.js`, and `examples/solutions-bananass-mts/bananass/2420.ts`. Each solution calculates the absolute difference between two numbers. [[1]](diffhunk://#diff-6f93bb82d0faa23fce314be88265500eac01ecbbe1929fba6de49b69af67a9a5R1-R22) …
=> docs(*): add more examples and related docs

websites/vitepress/ko/get-started/installation.md, websites/vitepress/ko/get-started/quick-start.md, websites/vitepress/ko/learn/other-useful-cli-commands.md, websites/vitepress/ko/learn/q-and-a.md, websites/vitepress/ko/learn/solving-a-problem-without-bananass.md
This pull request updates various Korean documentation files for the Banana Framework. The changes primarily improve clarity, consistency, and usability by refining phrasing, adding hyperlinks to relevant resources, and restructuring sections for better readability. Below are the most significant changes grouped by theme:
* Updated phrasing in `installation.md` to make descriptions more precise and added hyperlinks to external resources like [LTS Node.js](https://ko.wikipedia.org/wiki/%EC%9E%A5%EA%B8%B0_%EC%A7%80%EC%9B%90_%EB%B2%84%EC%A0%84) and [Git](https://git-scm.com/) for better context.
* Enhanced descriptions in `quick-start.md` by emphasizing file and folder types with formatting (e.g., *파일* and *폴더*) and linking to related documentation for modular and single-file logic.
* Added …
=> docs(websites-vitepress): update documentation

package-lock.json
=> chore(*): run `npm dedupe` for cleanup
