packages/bananass/src/commands/bananass-build/template.js
packages/bananass/src/commands/bananass-build/webpack.js
packages/bananass/src/utils/fs/getRootDir.js

This pull request includes several changes to improve the `bananass` package by updating comments, refining the webpack execution process, and enhancing the file structure. The most important changes are summarized below:
* [`packages/bananass/src/commands/bananass-build/template.js`](diffhunk://#diff-b5f27b403eb4f40a6a77b31a9d86aef95ef86913afbc8779ba275d54708f17efL4-R5): Updated comments to correct the property name from `webpackConfig` to `webpackConfigs` for accuracy.
* [`packages/bananass/src/commands/bananass-build/webpack.js`](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bL118-R141): Refined the webpack execution process by removing the `webpackAsync` function and directly using a promise within a try-catch block. Improved error handling and log …

refactor(bananass): improve documentation and shorten `webpackAsync` function

---

.github/sync-client.yml

This pull request includes a small change to the `.github/sync-client.yml` file. The change adds a new configuration file to be synchronized.
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1R64-R65): Added synchronization for the `.textlintrc.js` configuration file.

chore(sync-client): add `.textlintrc.js` to configuration sync

---

packages/bananass/src/cli.js
packages/bananass/src/commands/bananass-build/webpack.js

This pull request introduces a new feature to clean the output directory before emitting files and includes some minor documentation updates. The most important changes are:
* Added an option to clean the output directory before emitting files in the `program` of `packages/bananass/src/cli.js`.
* Implemented the `clean` option in the `build` function of `packages/bananass/src/commands/bananass-build/webpack.js`.
* Added a TODO comment for the new `options` parameter in the `build` function documentation in `packages/bananass/src/commands/bananass-build/webpack.js`.

feat(bananass): add option to clean output directory before emit

---

packages/bananass/src/commands/bananass-build/webpack.js

This pull request includes changes to the `packages/bananass/src/commands/bananass-build/webpack.js` file to improve code maintainability and error handling. The most important changes include the introduction of the `outputDir` variable to reduce redundancy and the enhancement of error logging.
Code maintainability improvements:
* Introduced the `outputDir` variable to store the resolved output directory path, reducing redundancy in the code. [[1]](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bR45) [[2]](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bL106-R107) [[3]](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bL143-R149)
Error handling improvements:
* Enhanced error logging by …

refactor(bananass-build): simplify output directory handling and improve logging

---

.github/sync-client.yml
babel.config.js
package-lock.json
package.json
packages/bananass-utils-console/babel.config.cjs
packages/bananass-utils-console/package.json
packages/bananass-utils-console/tsconfig.json

This pull request includes several changes focused on updating configuration files, improving TypeScript support, and refining the build and export processes for the `bananass-utils-console` package. Here are the most important changes:
* Updated `.github/sync-client.yml` to remove the `babel.config.js` synchronization entry.
* Added TypeScript as a dependency in `package.json`.
* Updated the `exports` field in `packages/bananass-utils-console/package.json` to include TypeScript declaration files.
* Added a `tsconfig.json` file to `packages/bananass-utils-console` to configure TypeScript compilation.
* Modified `babel.config.js` to prevent module transformation by Babel.
* Added a `babel.config.cjs` file to `packages/bananass-utils-console` to extend the root `babel.config.js`.
* Updated …

build: update Babel configuration and add TypeScript support

---

package-lock.json
packages/bananass-utils-console/package.json
packages/bananass-utils-console/src/logger.js
packages/bananass-utils-console/src/logger.test.js

This pull request includes several changes to the `bananass-utils-console` package, focusing on updating dependencies, modifying the `Logger` class, and improving the handling of text prefixes and logging methods.
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eR62-R64): Added `strip-ansi` as a development dependency.
* `packages/bananass-utils-console/src/logger.js`:
* Updated ESLint disable comments to include additional rules.
* Replaced `log` import with `ansi-colors` import.
* Introduced `#textPrefixDefault` and `#undeclaredValue` private fields.
* Refactored `log` and `debug` methods to handle parameters more flexibly and use `console.log` directly. …

test(bananass-utils-console): create `logger.test.js` and update `logger.js`

---

package-lock.json
packages/bananass-utils-console/package.json
packages/bananass-utils-console/src/spinner.test.js

This pull request introduces a new test file for the `spinner.js` module and adds a new development dependency to the `bananass-utils-console` package. The primary focus is on enhancing the test coverage for the `spinner.js` functionality.
* [`packages/bananass-utils-console/src/spinner.test.js`](diffhunk://#diff-c07c0032e447775e33efc82ed90e5c25c75d2e9437b5acb548190f9008e8874aR1-R156): Added comprehensive tests for `spinner.js`, including various scenarios such as starting, stopping, and changing the spinner text, as well as handling different spinner states like success, error, warning, and info.
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eR66): Added `get-stream` as a new development dependency to …

test(bananass-utils-console): add tests for `spinner` functionality and update dependencies

---

packages/bananass-utils-console/src/icons/index.js

This pull request introduces type definitions and annotations to the `packages/bananass-utils-console/src/icons/index.js` file to improve code readability and maintainability.
Key changes:
* Added a `SpinnerIcon` typedef to define the structure of spinner icons.
* Annotated various icon exports (`successIcon`, `errorIcon`, `warningIcon`, `infoIcon`, `bananassIcon`) with type information to specify that they are strings.
* Annotated `defaultSpinner` with the `SpinnerIcon` type to ensure it adheres to the defined structure.

refactor(bananass-utils-console): add typedef to `icons/index.js`

---

package-lock.json
package.json
website/package.json

This pull request includes changes to support the addition of a new `website` workspace. The most important changes include updating the `workspaces` configuration in `package.json` and adding a `package.json` file for the `website` workspace.
Workspace configuration:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L6-R7): Added the `website` directory to the list of workspaces.
New workspace setup:
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76R1-R8): Created a new `package.json` file for the `website` workspace with basic configuration including a `start` script.

chore: add `website` workspace and initialize `package.json`

---

.markdownlintignore

This pull request includes a small change to the `.markdownlintignore` file. The change standardizes the formatting by removing leading slashes from directory names and adds the `.next` directory to the ignore list.

chore: update `.markdownlintignore`

---

examples/solutions-readline-esm/package.json
examples/solutions-readline-esm/src/1000.js
package-lock.json

This pull request introduces a new example solution for the Baekjoon problem 1000 using ESM (ECMAScript Modules) in Node.js. The changes include the addition of a `package.json` file and the implementation of the solution in a new JavaScript file.
* [`examples/solutions-readline-esm/package.json`](diffhunk://#diff-dfaffaa92838021bc82c5f59c0831a2254b46a25409b25fffcc1f03a100cefa9R1-R9): Added a new `package.json` file to define the project as a module and include a script for running the solution.
* [`examples/solutions-readline-esm/src/1000.js`](diffhunk://#diff-595afe0897143ed9aae3e84be5c7a0649e33a6f2de08c405c87914e9033f6d61R1-R50): Implemented the solution for Baekjoon problem 1000 using ESM syntax, including imports from Node.js built-in modules and handling user input via the …

chore(examples-solutions-readline-esm): add examples for ESM solutions with readline

---

.github/workflows/lint.yml

This pull request includes an update to the `.github/workflows/lint.yml` file to enhance the security and stability of the linting process by pinning the `editorconfig-checker` version.
* [`.github/workflows/lint.yml`](diffhunk://#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2R14-R16): Added an environment variable `EC_VERSION` set to `3.0.3` for `editorconfig-checker` to ensure a specific version is used.
Ref: See, https://github.com/editorconfig-checker/editorconfig-checker/issues/409

fix: fix broken `editorconfig-checker` by pinning `EC_VERSION` in `lint.yml` workflow

---

package.json

This pull request includes a small change to the `package.json` file. The change specifies the required Node.js version for the project.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R6-R8): Added an `engines` field to specify that the project requires Node.js version 20.18.0 or higher.

chore: add `engines` field to `package.json`

---

packages/prettier-config-bananass/package.json
packages/prettier-config-bananass/src/index.js

This pull request includes changes to the `prettier-config-bananass` package to update dependencies and improve documentation. The most important changes include adding a `prepublishOnly` script, specifying `peerDependencies`, and enhancing module documentation.
Updates to dependencies and scripts:
* [`packages/prettier-config-bananass/package.json`](diffhunk://#diff-0fdaf27a6fc3a9c98ce068e2f60dd6fa1d2a82cfc232695581bcae3256c32d76L32-R38): Added a `prepublishOnly` script to run the build process before publishing, and specified `prettier` as a peer dependency.
Enhancements to documentation:
* [`packages/prettier-config-bananass/src/index.js`](diffhunk://#diff-5704c175b00dfba9748074a44221d8bdeafc9a341ed6c6107bb94b85ee8394f5L5-R12): Added a link to the Prettier options documentation in the …

refactor(prettier-config-bananass): add peerDependencies, prepublish script, type support

---

.github/workflows/lint.yml

This reverts commit 4c92a0bed2775aa9e9c475a2369b53074d7dbd39.
Bug was fixed in `editorconfig-checker` repository. So it is no longer needed.

revert: "fix: fix broken `editorconfig-checker` by pinning `EC_VERSION` in `lint.yml` workflow (#58)"

---

packages/eslint-config-bananass/src/rules/import-helpful-warnings.js

This pull request includes updates to the ESLint configuration rules in the `import-helpful-warnings.js` file to support additional JavaScript module formats.
Key changes include:
* Updated test file patterns to include `mjs` and `cjs` extensions for better compatibility with different module formats.
* Added a new pattern to recognize ESLint configuration files with `mjs` and `cjs` extensions.

fix(eslint-config-bananass): support additional file extensions in `import/no-extraneous-dependencies` rule

---

packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json

This pull request includes updates to the `peerDependencies` versions in the `eslint-config-bananass` and `prettier-config-bananass` packages to ensure compatibility with specific versions of `eslint` and `prettier`.
* [`packages/eslint-config-bananass/package.json`](diffhunk://#diff-e820b85e94fd5b26012547982c44a557398b5c3dc850ac0c4094d184dfd5bcbcL39-R39): Changed `peerDependencies` version for `eslint` from ">=9.0.0" to "^9.0.0".
* [`packages/prettier-config-bananass/package.json`](diffhunk://#diff-0fdaf27a6fc3a9c98ce068e2f60dd6fa1d2a82cfc232695581bcae3256c32d76L38-R38): Changed `peerDependencies` version for `prettier` from ">=3.0.0" to "^3.0.0".

refactor(*-config-bananass): update `peerDependencies` to use caret versioning for eslint and prettier

---

packages/eslint-config-bananass/src/rules/eslint-suggestions.js
packages/eslint-config-bananass/src/rules/import.test.js

This pull request includes updates to the ESLint configuration in the `packages/eslint-config-bananass` directory. The most important changes involve modifying the rule for unused expressions and a minor documentation update in the test file.
ESLint rule modification:
* [`packages/eslint-config-bananass/src/rules/eslint-suggestions.js`](diffhunk://#diff-1f40e810e232a16ad4be9fc96b8e5f9c8601d1e880c06207da6297c8f80c51dfL956-R956): Changed the `no-unused-expressions` rule to enforce checks for JSX expressions.
Documentation update:
* [`packages/eslint-config-bananass/src/rules/import.test.js`](diffhunk://#diff-d9bb1e9956c01e11d0b97a58cbb82ddeddb8f93cfb33197200fde583f374b1fcL2-R2): Corrected the file overview comment to remove unnecessary whitespace.

fix(eslint-config-bananass): enforce JSX usage in `no-unused-expressions` rule

---

.github/dependabot.yml

This pull request includes updates to the `.github/dependabot.yml` file to improve dependency management and assignment. The changes introduce new assignees and reviewers, organize dependencies into groups, and adjust the versioning strategy.
Dependency management improvements:
* Added `assignees` and `reviewers` fields to ensure that 'lumirlumir' is assigned to and reviews the dependency updates for both npm and GitHub Actions.
* Organized npm dependencies into groups (`bananass`, `babel`, `react`, and `next`) to better manage related dependencies.
* Changed the `versioning-strategy` to 'increase' for npm dependencies to ensure a consistent update strategy.

chore(dependabot): update configuration to include groups, assignees, and reviewers

---

package-lock.json
package.json
website/package.json

This pull request includes changes to the `package.json` files to clean up the workspace configuration by removing the `website` directory. The most important changes include the removal of the `website` workspace and its associated `package.json` file.
Workspace configuration changes:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12-R12): Removed the `website` directory from the list of workspaces.
* [`website/package.json`](diffhunk://#diff-fae242fbf77a8a9d52625664bc36ea12316586f8a716b41137d897a2b7e3df76L1-L8): Deleted the `package.json` file for the `website` directory, including its scripts and metadata.

chore: remove `website` package and update workspace configuration

---

.github/ISSUE_TEMPLATE/config.yml

This pull request includes a small change to the `.github/ISSUE_TEMPLATE/config.yml` file. The change disables blank issues and adds a contact link to the official documentation of the Bananass Framework.
* [`.github/ISSUE_TEMPLATE/config.yml`](diffhunk://#diff-1c0d972ee49103af56fd608a77a28e1eb12f6908f263f0f183d46868fdcd8ea2R1-R5): Disabled blank issues and added a contact link to the official documentation of the Bananass Framework.

chore: create `ISSUE_TEMPLATE/config.yml`

---

packages/bananass-utils-console/package.json
packages/bananass-utils-console/tsconfig.json
packages/bananass-utils/tsconfig.json
packages/bananass/tsconfig.json

This pull request includes changes to the TypeScript configuration and package settings for several packages to improve compatibility and module resolution. The most important changes include adding `typesVersions` to the `package.json` file and updating the `tsconfig.json` files to target `ESNext` and use `Node` module resolution.
Updates to `package.json`:
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eR25-R40): Added `typesVersions` to specify different type definitions for different modules.
Updates to `tsconfig.json`:
* [`packages/bananass-utils-console/tsconfig.json`](diffhunk://#diff-00d843065b36c05dd508bb0a94f06c16cc20bb2c4a760080908e336b719d3232L6-R8): Updated to target `ESNext` and use `Node` …

feat(bananass-utils-console): add `typesVersions` to `package.json` for improved type definitions

---

.editorconfig-checker.json
docs/archived.md

This pull request includes a small change to the `.editorconfig-checker.json` file. The change removes the exclusion of the `docs/archived.md` file from the configuration. 
* [`.editorconfig-checker.json`](diffhunk://#diff-ffc189b5d4f8c2eb9a171e067565fbfe9ecba9a5b717d236cbf22497973fc4a3L2-R2): Removed the exclusion of the `docs/archived.md` file from the `Exclude` list.

chore: update `.editorconfig-checker.json` to remove excluded files and tidy up `docs/archived.md`

---

.github/sync-client.yml
scripts/vercel-ignore-command.sh
websites/eslint-config-bananass-react/vercel.json
websites/eslint-config-bananass/vercel.json

This pull request includes several changes to improve the build process and configuration for various projects. The most important changes include adding a new script to ignore builds for certain pull requests, updating the Vercel configuration files, and modifying the sync-client configuration.
* Added a new script `vercel-ignore-command.sh` to ignore builds for pull requests created by `dependabot[bot]` if the branch is not `main`. (`scripts/vercel-ignore-command.sh`)
* Updated the Vercel configuration for `eslint-config-bananass-react` to include build, ignore, and install commands, and specified the output directory and regions. (`websites/eslint-config-bananass-react/vercel.json`)
* Updated the Vercel configuration for `eslint-config-bananass` to include build, ignore, and install …

chore: add Vercel ignore command script and update configuration for multiple websites

---

packages/eslint-config-bananass-react/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json

This pull request includes changes to the `package.json` files of several packages to exclude test and spec files from the published packages. 
Changes to exclude test and spec files:
* [`packages/eslint-config-bananass-react/package.json`](diffhunk://#diff-263baf2bd4636e9041e07fa4d170bdde1545c6a48947ab5ff1f511e289d53356R13-R14): Added exclusions for `src/**/*.test.js` and `src/**/*.spec.js` files.
* [`packages/eslint-config-bananass/package.json`](diffhunk://#diff-e820b85e94fd5b26012547982c44a557398b5c3dc850ac0c4094d184dfd5bcbcR13-R14): Added exclusions for `src/**/*.test.js` and `src/**/*.spec.js` files.
* [`packages/prettier-config-bananass/package.json`](diffhunk://#diff-0fdaf27a6fc3a9c98ce068e2f60dd6fa1d2a82cfc232695581bcae3256c32d76L12-R14): Changed the `files` field to include the …

chore: exclude test files from `package.json` `files` array in eslint and prettier configs

---

packages/eslint-config-bananass/src/rules/eslint-suggestions.js
packages/eslint-config-bananass/src/rules/import-helpful-warnings.js

This pull request includes changes to the ESLint configuration files to improve code quality and add support for VitePress configuration files. The most important changes are:
Improvements to ESLint rules:
* [`packages/eslint-config-bananass/src/rules/eslint-suggestions.js`](diffhunk://#diff-1f40e810e232a16ad4be9fc96b8e5f9c8601d1e880c06207da6297c8f80c51dfL852-L856): Removed the rule that disallowed `ForOfStatement` due to its requirement for regenerator-runtime and preference for array iterations.
Support for additional configuration files:
* [`packages/eslint-config-bananass/src/rules/import-helpful-warnings.js`](diffhunk://#diff-79ecb0b15195b09eb33fa02b122f31c3b379af45d9104d40cad485e5aaa80dd9R73): Added support for VitePress configuration files by including them in the list of files to …

feat(eslint-config-bananass): remove unnecessary `ForOfStatement` warning and add Vitepress config to import warnings

---

package-lock.json
package.json
packages/bananass/babel.config.cjs
packages/bananass/package.json

This pull request includes several changes to the `packages/bananass` package and the overall project configuration. The most important changes involve the removal of the Babel configuration, updates to the `package.json` scripts and exports, and adjustments to the files included in the package.
* [`packages/bananass/babel.config.cjs`](diffhunk://#diff-71c0b4cdbbbd259d8127e792bcb71a898be780767c98686dfcc9fb5ce9a9c026L1-L3): Removed the Babel configuration file as it is no longer needed.
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432L9-R23): Updated the `exports` field to point to the source files instead of the build files, and adjusted the `bin` field to reference the source CLI file.
* …

build(bananass): delete babel to simplify build process as Bananass only support node >= 20.18.0

---

packages/bananass/src/cli/bananass-build.js
packages/bananass/src/commands/bananass-build/webpack.js
packages/bananass/src/core/conf/default-config-object/default-config-object.js
packages/bananass/src/core/constants.js
packages/bananass/src/core/types.js

This pull request includes changes to the `bananass` package, focusing on improvements to the build configuration and code simplification. The most important changes include removing unused constants, adding a new configuration option for the output directory, and updating related functions to use this new option.
* [`packages/bananass/src/cli/bananass-build.js`](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L13-R13): Added `outDir` to the build configuration options and updated the command description to reflect this change. Removed unused constants from imports. [[1]](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L13-R13) [[2]](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776R41-R55)
* …

feat(bananass): add `outDir` option to `build` command

---

packages/bananass/src/cli/bananass-build.js
packages/bananass/src/commands/bananass-build/webpack.js
packages/bananass/src/core/conf/default-config-object/default-config-object.js
packages/bananass/src/core/conf/default-config-object/index.js
packages/bananass/src/core/conf/index.js
packages/bananass/src/core/constants.js
packages/bananass/src/core/types.js

This pull request includes several changes to the `bananass` package, primarily focusing on refactoring and adding new configuration options. The most important changes include the addition of an `entryDir` configuration option, refactoring of the `default-config-object`, and removal of unused code.
* Added `entryDir` configuration option to the `defaultConfigObject.build` object and updated related files to use this new option. [[1]](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L41-R43) [[2]](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bR46) [[3]](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bL116-R117) [[4]](diffhunk://#diff-52a8798a5e892009d2bf6b96aaff12cc552d06b6a08c3338dacfcfb2f1 …

feat(bananass): add `entryDir` option to `build` command

---

packages/bananass/src/cli/bananass-build.js

BREAKING CHANGE
This pull request includes a change to the `bananassBuild` function in the `bananass-build.js` file. The change modifies the argument type for the `problems` parameter to be required instead of optional.
* [`packages/bananass/src/cli/bananass-build.js`](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L43-R43): Changed the `problems` argument from optional (`[problems...]`) to required (`<problems...>`).

feat!(bananass): change `problems` argument from optional to required in `build` command

---

package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass-utils/package.json
packages/bananass/package.json
packages/eslint-config-bananass-react/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json

This pull request includes updates to various `package.json` files to standardize the build scripts by using `shx` for copying files. The changes ensure consistency and cross-platform compatibility in the build process.
Standardization of build scripts:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R70): Added `shx` as a dependency.
* [`packages/bananass-utils-console/package.json`](diffhunk://#diff-14dc0ab8d918f740c0f0d225fcfbbfdbf6620ab25f1e833d884d3878b35a9a0eL73-R73): Updated the `build` script to use `shx` for copying `LICENSE.md` and `README.md` files.
* [`packages/bananass-utils-vitepress/package.json`](diffhunk://#diff-e9935f58a17308158af0563ed80b22f02cba32b411c4e1bd2e2acb76593734a9L77-R77): Updated the `build` script to use …

build: replace `cp` with `shx cp` in build scripts for cross-platform compatibility

---

.github/workflows/pull-request.yml

This pull request includes a small change to the `.github/workflows/pull-request.yml` file. The change adds the `synchronize` event type to the `pull_request_target` trigger. 
Changes in event types:
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L5-R5): Added `synchronize` to the list of `pull_request_target` event types.

ci(*): update `pull-request.yml` workflow to include `synchronize` event

---

.github/workflows/pull-request.yml

This pull request includes a small but important change to the `.github/workflows/pull-request.yml` file. The change updates the condition for the `labeler` job to also trigger when the pull request action is synchronized.
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L145-R145): Updated the `if` condition for the `labeler` job to include `github.event.action == 'synchronize'`.

ci(*): update `pull-request.yml` labeler condition to include `synchronize` event

---

package-lock.json
package.json

This pull request includes changes to the `package.json` file to update workspace configuration and modify build and test scripts to exclude a specific package.
Workspace configuration:
* Added the current directory (`"."`) to the list of workspaces.
Script modifications:
* Updated the `test` script to ignore the `npm-bananass` package.
* Updated the `build` script to ignore the `npm-bananass` package.

chore(npm-bananass): update workspace configuration and adjust test/build commands to ignore `npm-bananass`

---

package-lock.json
packages/bananass/package.json
packages/bananass/src/cli/bananass-build.js
packages/bananass/src/commands/bananass-build/template-fs.cjs
packages/bananass/src/commands/bananass-build/template-rl.cjs
packages/bananass/src/commands/bananass-build/webpack.js

This pull request includes several changes to the `bananass` package to switch from using Babel to using esbuild for JavaScript and TypeScript bundling. The most important changes include updating dependencies, modifying build commands, and updating webpack configurations.
* Added `esbuild-loader` to `packages/bananass/package.json` to enable esbuild integration with webpack.
* Updated the build command description in `packages/bananass/src/cli/bananass-build.js` to reflect the switch from Babel to esbuild.
* Modified dynamic require handling in `packages/bananass/src/commands/bananass-build/template-fs.cjs` and `packages/bananass/src/commands/bananass-build/template-rl.cjs` to support both ES modules and CommonJS modules. [[1]](diffhunk://#diff-10967f3986443f0da26c5ef2346ba9ab9ffa92382931 …

feat(bananass): add TypeScript and ESM support for `build` command

---

packages/bananass/src/commands/bananass-build/webpack.js
packages/bananass/src/core/constants.js

This pull request includes changes to the `packages/bananass` module to enhance the build process and improve code documentation. The most important changes include the addition of a Webpack banner plugin, the introduction of a new constant for the Webpack banner, and the reorganization of exports in the `constants.js` file.
* [`packages/bananass/src/commands/bananass-build/webpack.js`](diffhunk://#diff-0ce95c8c9e2a9153c60042f1f9db2f62324e019f7980eb2e8ee8a5001fd6e34bR127-R131): Added the Webpack BannerPlugin to include a banner in the generated files.
* [`packages/bananass/src/core/constants.js`](diffhunk://#diff-97d6046c52dcaa9f59ecd0bc5a1ed48d3a91d2c8159901b86ba0b4932b532886R37-R63): Introduced a new constant `WEBPACK_BANNER` for the Webpack banner content.
* …

feat(bananass): add webpack banner plugin with generated file information

---

package-lock.json
packages/bananass/package.json

This pull request includes a small change to the `packages/bananass/package.json` file. The change adds a new binary entry for `b` that points to `src/cli.js`.
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432R14): Added a new binary entry for `b` that points to `src/cli.js`.

feat(bananass): add shorthand command `b` for CLI

---

packages/bananass/src/cli/bananass-build.js
packages/bananass/src/cli/bananass-discussion.js
packages/bananass/src/cli/bananass-home.js
packages/bananass/src/cli/bananass-open.js
packages/bananass/src/cli/bananass-repo.js

This pull request makes consistent changes across multiple CLI functions in the `packages/bananass/src/cli` directory. The primary change involves modifying the `logger` function to use `configObject.console` instead of `options`.
Changes to logger function:
* [`packages/bananass/src/cli/bananass-build.js`](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L79-R79): Changed the `logger` function to use `configObject.console`
* [`packages/bananass/src/cli/bananass-discussion.js`](diffhunk://#diff-4c48cc7ffa1263ce11a655a343ce65a17a24698cf8e694a10ea92045e323a0b6L71-R71): Changed the `logger` function to use `configObject.console`
* [`packages/bananass/src/cli/bananass-home.js`](diffhunk://#diff-c12d0a891fa6e9d26f5f7592e03138038d5898b95d08fcaa07580ff517172eeeL68- …

fix(bananass): correct `logger` calls in cli to use `configObject.console`

---

.github/dependabot.yml

This pull request includes a small change to the `.github/dependabot.yml` file. The change adds a new pattern to the `bananass` group for dependency updates.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R16): Added the pattern `'bananass-utils-vitepress'` to the `bananass` group.

chore(*): update `dependabot.yml` and delete `bananass-dataset` directory

---

babel.config.js
packages/bananass-utils-console/tsconfig.json
packages/bananass-utils-vitepress/tsconfig.json
packages/bananass/package.json
packages/bananass/tsconfig.json
packages/eslint-config-bananass-react/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json

This pull request includes several changes across multiple configuration files to simplify the exclusion patterns for test files by removing references to `*.spec.js` files. The most important changes are as follows:
Changes to ignore/exclude patterns:
* [`babel.config.js`](diffhunk://#diff-09c56b2bf95de2a608a36afef3b6893146a959d6739be0a154dc9c9f02d80f24L10-R10): Updated the `ignore` array to remove `**/*.spec.js` from the list of ignored files.
* [`packages/bananass-utils-console/tsconfig.json`](diffhunk://#diff-00d843065b36c05dd508bb0a94f06c16cc20bb2c4a760080908e336b719d3232L15-R15): Modified the `exclude` array to remove `src/**/*.spec.js` from the list of excluded files.
* [`packages/bananass-utils-vitepress/tsconfig.json`](diffhunk://#diff-16de8031cfd35c972e9f88018f3112664936f6e0fa4ca …

chore(*): remove `.spec.js` files from ignore and exclude lists in configuration files

---

packages/eslint-config-bananass/src/rules/import/import-static-analysis.js
packages/eslint-config-bananass/src/rules/node/node.js
packages/eslint-config-bananass/src/rules/react/react.js

This pull request includes several changes to the ESLint configuration files in the `packages/eslint-config-bananass` directory. The changes primarily focus on updating rule descriptions and modifying rule settings for better code analysis.
* [`packages/eslint-config-bananass/src/rules/import/import-static-analysis.js`](diffhunk://#diff-a415fbe05c5cbf8feb435325f7f58bcced3a908ae247260a9b82300b1f1457ffR117): Added a link to an issue in the rule description for better context.
* [`packages/eslint-config-bananass/src/rules/node/node.js`](diffhunk://#diff-c96c91af708b289359a5b68fb41a21628063ede30d509cc8901b9063cacd9309L113-R113): Updated the description to clarify the use of `require()` expressions.
* [`packages/eslint-config-bananass/src/rules/react/react.js`](diffhunk://#diff-d2e14b50ea9ff3e2 …

fix(eslint-config-bananass): update `react/curly-brace-presence` to follow default options

---

packages/eslint-config-bananass/src/rules/eslint/eslint.test.js
packages/eslint-config-bananass/src/rules/import/import.test.js
packages/eslint-config-bananass/src/rules/jsx-a11y/jsx-a11y.test.js
packages/eslint-config-bananass/src/rules/next/next.test.js
packages/eslint-config-bananass/src/rules/node/node.test.js
packages/eslint-config-bananass/src/rules/react-compiler/react-compiler.test.js
packages/eslint-config-bananass/src/rules/react-hooks/react-hooks.test.js
packages/eslint-config-bananass/src/rules/react/react.test.js
packages/eslint-config-bananass/src/rules/stylistic-js/stylistic-js.test.js

This pull request adds test descriptions to several test files in the `packages/eslint-config-bananass` directory to improve the readability and organization of the tests. The most important changes include the addition of `describe` blocks to group related tests together.
Test organization improvements:
* [`packages/eslint-config-bananass/src/rules/eslint/eslint.test.js`](diffhunk://#diff-c060423761a34eda8493c1e0d772676fa13210a10ddc0a601bffa94ef5b3cd63R26): Added `describe('eslint', () => { ... })` block to group ESLint-related tests. [[1]](diffhunk://#diff-c060423761a34eda8493c1e0d772676fa13210a10ddc0a601bffa94ef5b3cd63R26) [[2]](diffhunk://#diff-c060423761a34eda8493c1e0d772676fa13210a10ddc0a601bffa94ef5b3cd63R46)
* [`packages/eslint-config-bananass/src/rules/import/import.test.js`](diff …

test(eslint-config-bananass): restructure test descriptions for clarity and consistency

---

packages/eslint-config-bananass/src/configs/tsx-next.js
packages/eslint-config-bananass/src/configs/tsx-react.js
packages/eslint-config-bananass/src/index.js
packages/eslint-config-bananass/src/rules/react/react.js
websites/eslint-config-bananass/config.js

This pull request includes significant updates to the ESLint configuration for TypeScript and React projects. The changes introduce new configurations for `tsx-react` and `tsx-next`, and update existing configurations to support `.tsx` files.
New configurations:
* [`packages/eslint-config-bananass/src/configs/tsx-next.js`](diffhunk://#diff-7e6986b8aa252958b9da97c71d62e00f1895da50f896ceb71305ba34671b403aR1-R81): Added a new configuration for projects using TypeScript and Next.js. This configuration includes relevant plugins and rules.
* [`packages/eslint-config-bananass/src/configs/tsx-react.js`](diffhunk://#diff-1f99df34d53d43dd73a2dbe7af4e50a96ff8a4d5b36cbb7fc8a9296ab0bc22fdR1-R75): Added a new configuration for projects using TypeScript and React. This configuration includes relevant …

feat(eslint-config-bananass): add new `tsx` configs

---

packages/bananass-utils-console/src/icons/icons.js
packages/bananass-utils-console/src/spinner/spinner.js

This pull request includes several changes to the `packages/bananass-utils-console` package, focusing on improving the spinner functionality and code documentation. The key changes involve renaming typedefs, adding detailed JSDoc comments, and modifying the spinner's color and behavior.
* Renamed `SpinnerIcon` to `SpinnerStyle` and updated corresponding typedefs in `icons.js` and `spinner.js`. [[1]](diffhunk://#diff-d3f16eb3ff3fa7e044b861f681f7554eca8a0d838ebe6ef5e26e2adcdb008683L17-R17) [[2]](diffhunk://#diff-d3f16eb3ff3fa7e044b861f681f7554eca8a0d838ebe6ef5e26e2adcdb008683L37-R37) [[3]](diffhunk://#diff-8b2068e270f808f9232fbc4c64ad8c7667268d13530c4dc264e9584a1afbcdebR22-R54)
* Added detailed JSDoc comments for the `Spinner` class methods and properties, including examples and parameter …

feat(bananass-utils-console)!: add type support for `spinner` and update default color

---

packages/bananass/src/commands/bananass-bug/bug.js
packages/bananass/src/commands/bananass-build/build.js
packages/bananass/src/commands/bananass-discussion/discussion.js
packages/bananass/src/commands/bananass-home/home.js
packages/bananass/src/commands/bananass-open/open.js
packages/bananass/src/commands/bananass-repo/repo.js
packages/bananass/src/commands/bananass-run/run.js

This pull request includes changes to multiple command files in the `bananass` package to ensure the `showIcon` parameter is set to `true` when starting the spinner animation. This change provides a consistent user interface experience across different commands.
Changes to spinner animation:
* [`packages/bananass/src/commands/bananass-bug/bug.js`](diffhunk://#diff-c49c2ac0f48f162fb6dd63de6eaaf35f7fc82f0372fc582a3332539634eb576bL58-R58): Set `showIcon` to `true` in the `bananass` function call within the `bug` command.
* [`packages/bananass/src/commands/bananass-build/build.js`](diffhunk://#diff-5b3f690c580caae1e82d3789dd6e78d9b694ac24acc51e672b297b524521fda4L80-R80): Set `showIcon` to `true` in the `bananass` function call within the `build` command.
* …

fix(bananass): enable bananass icon display in spinner messages across multiple commands

---

package.json

This pull request includes a change to the `package.json` file to update the publish script. The change modifies the `publish-package` script to use the `next` pre-distribution tag instead of the `canary` tag.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-R19): Updated the `publish-package` script to use `next` pre-distribution tag instead of `canary`.

chore(*): update `publish-package` script to use 'next' pre-dist tag

---

packages/bananass/src/core/fs/find-root-dir/find-root-dir.js
packages/bananass/src/core/fs/find-root-dir/find-root-dir.test.js

This pull request includes several changes to the `find-root-dir` functionality in the `bananass` package. The changes focus on improving error messaging and ensuring compatibility with test mocks.
* [`find-root-dir.js`](diffhunk://#diff-aed2769c5bf3d27e1aa5d4b258ebffc32608a930d0f9f6a9d4c31e6416de2122L45-R55): Enhanced the error messages for Git command failures and missing `PACKAGE_JSON` to improve clarity.
* [`find-root-dir.js`](diffhunk://#diff-aed2769c5bf3d27e1aa5d4b258ebffc32608a930d0f9f6a9d4c31e6416de2122L10-R11): Added comments to avoid destructuring imports for `child_process` and `fs` due to mock usage in tests.
* [`find-root-dir.test.js`](diffhunk://#diff-66083096c3b9bfd47416706df5b93b42295382b172a5195d7cd2a56a7eb823c3L2-R2): Corrected the file name in the file overview comment.

refactor(bananass): refactor `find-root-dir.js` to improve error messages and update test file overview

---

packages/bananass/src/cli/bananass-bug.js
packages/bananass/src/cli/bananass-build.js
packages/bananass/src/cli/bananass-discussion.js
packages/bananass/src/cli/bananass-home.js
packages/bananass/src/cli/bananass-info.js
packages/bananass/src/cli/bananass-open.js
packages/bananass/src/cli/bananass-repo.js
packages/bananass/src/cli/bananass-run.js
packages/bananass/src/core/conf/config-loader/config-loader.js
packages/bananass/src/core/conf/config-loader/config-loader.test.js

This pull request focuses on simplifying the configuration loading process across multiple command files by removing the explicit import and usage of `defaultConfigObject` in favor of using a default parameter within the `configLoader` function. Additionally, the test cases are updated to reflect these changes.
Key changes include:
* Removed `defaultConfigObject` import and usage from multiple CLI command files (`bananass-bug.js`, `bananass-build.js`, `bananass-discussion.js`, `bananass-home.js`, `bananass-info.js`, `bananass-open.js`, `bananass-repo.js`, `bananass-run.js`). [[1]](diffhunk://#diff-196f36c2928080b1421ad5f1091b6715ba428f781678296dc43ee5fd1b7f4bd4L12-R12) [[2]](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L12-R12) …

refactor(bananass): update `configLoader` to use `defaultConfigObject` and improve test cases

---

packages/bananass/src/cli/bananass-bug.js
packages/bananass/src/cli/bananass-build.js
packages/bananass/src/cli/bananass-discussion.js
packages/bananass/src/cli/bananass-home.js
packages/bananass/src/cli/bananass-info.js
packages/bananass/src/cli/bananass-open.js
packages/bananass/src/cli/bananass-repo.js
packages/bananass/src/cli/bananass-run.js
packages/bananass/src/core/conf/config-loader/config-loader.js
packages/bananass/src/core/conf/config-loader/config-loader.test.js
packages/bananass/src/core/constants.js

This pull request includes several changes to the `bananass` package, primarily focusing on simplifying the codebase and improving the configuration loader functionality. The most important changes include modifying the `configLoader` function to return the configuration object directly, adding validation for supported configuration file extensions, and updating the corresponding test cases.
* Removed unnecessary destructuring of `config` in the `configLoader` function and directly returned the configuration object in various CLI command files. [[1]](diffhunk://#diff-196f36c2928080b1421ad5f1091b6715ba428f781678296dc43ee5fd1b7f4bd4L53-R53) [[2]](diffhunk://#diff-2303a83467664c32322f8bcdc363e8348ef50a284af4d2dd7501dcf64c21f776L58-R58) …

refactor(bananass): refactor and enhance `configloader` to validate supported file extensions

---

.github/workflows/lint.yml
.github/workflows/test.yml

This pull request includes updates to the GitHub workflows to enhance security by setting read-only permissions for contents. The most important changes are:
Workflow updates:
* [`.github/workflows/lint.yml`](diffhunk://#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2R10-R12): Added `permissions` section to set contents to read-only.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R10-R12): Added `permissions` section to set contents to read-only.

ci(*): add permissions to read contents in `lint.yml` and `test.yml` workflows

---

.github/workflows/sync-client.yml

This pull request includes a small but important change to the GitHub Actions workflow configuration file. The change adds read permissions for contents in the `sync-client` job.
* [`.github/workflows/sync-client.yml`](diffhunk://#diff-254f50149bdf646bb0bb19197c9fa73d054fdb550909072ed57e0b5bcc39a197R7-R9): Added `permissions` section to allow read access to contents.

ci(*): update permissions in `sync-client.yml` to allow read access to contents

---

lint-staged.config.js

This pull request includes a small change to the `lint-staged.config.js` file. The change extends ESLint to also check TypeScript files.
* [`lint-staged.config.js`](diffhunk://#diff-29c15f0b5d8d1144bd22153c302cde16c2de092d65b122a618cbdb3023336346L6-R6): Updated the file extensions for ESLint to include TypeScript files (`*.ts`, `*.mts`, `*.cts`, `*.tsx`).

chore(*): update `lint-staged.config.js` to support TypeScript file extensions

---

packages/bananass/src/commands/bananass-build/build.js
packages/eslint-config-bananass/src/configs/js.js
packages/eslint-config-bananass/src/configs/jsx-next.js
packages/eslint-config-bananass/src/configs/jsx-react.js
packages/eslint-config-bananass/src/configs/ts.js
packages/eslint-config-bananass/src/configs/tsx-next.js
packages/eslint-config-bananass/src/configs/tsx-react.js
packages/eslint-config-bananass/src/settings.js

This pull request includes changes to the `bananass` package to enhance the build process and update ESLint configurations. The most important changes include adding a new setting for Node.js resolver configuration and updating various ESLint configuration files to include this new setting.
* [`packages/bananass/src/commands/bananass-build/build.js`](diffhunk://#diff-5b3f690c580caae1e82d3789dd6e78d9b694ac24acc51e672b297b524521fda4R137): Added `resolvedEntryDir` to the `include` array for JavaScript files to ensure proper inclusion of node modules.
* [`packages/eslint-config-bananass/src/settings.js`](diffhunk://#diff-f3313674a9f29402cc0fbfc6fa06d9c88b5b8caa48ac94dca0b71f547b85514fR9-R16): Added a new `node` setting with resolver configuration for extensions and main files.
* …

fix(bananass): incorrect bundling in javascript-ESM causing unexpected build results

---

package-lock.json
websites/vitepress/.vitepress/config/shared.js
websites/vitepress/package.json

This pull request introduces a new Codecov Vite plugin to the Vitepress configuration and updates the dependencies accordingly. The most important changes include the addition of the Codecov Vite plugin and the `is-interactive` package, as well as the necessary modifications to the Vitepress configuration to incorporate these new tools.
* [`websites/vitepress/.vitepress/config/shared.js`](diffhunk://#diff-73876f6a978dec27dfeeaa8c70437d5664ae37af70af0cda625a8d54373d237bR16-R17): Added imports for the Codecov Vite plugin and `is-interactive`, and updated the Vite configuration to include the Codecov Vite plugin with specific settings, ensuring it only runs in CI environments. [[1]](diffhunk://#diff-73876f6a978dec27dfeeaa8c70437d5664ae37af70af0cda625a8d54373d237bR16-R17) …

chore(websites-vitepress): add `@codecov/vite-plugin` and update related configs for bundle analysis

---

packages/bananass/src/cli/bananass-discussion.js

This pull request includes an enhancement to the `discussion` function in the `bananass-discussion.js` file. The change adds new aliases to improve user accessibility and command recognition.
Enhancements to command aliases:
* [`packages/bananass/src/cli/bananass-discussion.js`](diffhunk://#diff-4c48cc7ffa1263ce11a655a343ce65a17a24698cf8e694a10ea92045e323a0b6R45-R46): Added new aliases 'question' and 'questions' to the `discussion` function to provide more intuitive command options for users.

feat(bananass): add `question` and `questions` alias to `bananass discussion` cli command

---

package-lock.json
websites/vitepress/ko/learn/how-to-parse-input-value.md
websites/vitepress/package.json

This pull request includes minor updates to the Korean documentation and a version bump for a plugin in the `websites/vitepress` package.
Documentation update:
* [`websites/vitepress/ko/learn/how-to-parse-input-value.md`](diffhunk://#diff-23393c5e02c45691527083acfcadef7dc125af1cfcad10f20412864a0a83fbfdL275-R275): Improved the code example by simplifying the `map` function call to directly use `Number` instead of a lambda function.
Dependency update:
* [`websites/vitepress/package.json`](diffhunk://#diff-10ef64608fffd18cd9a3d2a3b2adb3361c324abf4a0040a210720ab259c6acd2L19-R19): Updated the version of `vitepress-plugin-group-icons` from `^1.3.6` to `^1.3.7`.

chore(deps-dev): bump `vitepress-plugin-group-icons` from `1.3.6` to `1.3.7`

---

.github/sync-client.yml
packages/eslint-config-bananass/src/rules/node/node.js

This pull request includes updates to configuration files and adjustments to ESLint rules. The most important changes are the addition of a new configuration file and an update to an existing ESLint rule.
Configuration updates:
* [`.github/sync-client.yml`](diffhunk://#diff-93bc202766315b6269beef308a6ad30ed3e86938ddbfa31b49e030f2263695f1R73-R74): Added `eslint.config.mjs` to the list of files to be synced.
ESLint rule adjustments:
* [`packages/eslint-config-bananass/src/rules/node/node.js`](diffhunk://#diff-c96c91af708b289359a5b68fb41a21628063ede30d509cc8901b9063cacd9309L110-R115): Modified the `n/no-missing-import` rule to ignore type imports by adding an options object.

fix(eslint-config-bananass): update `no-missing-import` rule to ignore type imports and add `eslint.config.mjs` to `sync-client.yml`

---

CHANGELOG.md
packages/bananass-utils-console/tsconfig.json
packages/bananass-utils-vitepress/tsconfig.json
packages/bananass/tsconfig.json
packages/create-bananass/tsconfig.json

And also fix a heading in `CHANGELOG.md`
---
This pull request includes changes to the `CHANGELOG.md` file and updates to the TypeScript configuration files across multiple packages to support additional JavaScript module formats.
Changes to documentation:
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL1-R1): Updated the title from "bananass" to "Change Log" and added links to Releases and Tags on GitHub.
Updates to TypeScript configuration:
* [`packages/bananass-utils-console/tsconfig.json`](diffhunk://#diff-00d843065b36c05dd508bb0a94f06c16cc20bb2c4a760080908e336b719d3232L14-R14): Included support for `.mjs` and `.cjs` module formats in addition to `.js` files.
* [`packages/bananass-utils-vitepress/tsconfig.json`](diffhunk://#diff-00d8 …

chore(*): update `tsconfig.json` to include patterns to support `.mjs` and `.cjs` files

---

packages/bananass/src/commands/bananass-run/run.js
packages/bananass/src/core/constants.js
packages/bananass/src/core/structs/solution/solution.js
websites/vitepress/.vitepress/config/en.js
websites/vitepress/.vitepress/config/ko.js

This pull request includes several changes to improve type handling, update constants, and ensure consistency in URLs across the codebase. The most important changes include replacing `@ts-ignore` with `@ts-expect-error`, adding a new constant for the NPM URL, and updating various configurations to use this new constant.
Improvements to type handling:
* [`packages/bananass/src/commands/bananass-run/run.js`](diffhunk://#diff-e32949e4dff2549ab48c17b6a98d88eff1f009162d34c041087ba9fdd1480ce2L113-R113): Changed `@ts-ignore` to `@ts-expect-error` for better type checking.
* [`packages/bananass/src/core/structs/solution/solution.js`](diffhunk://#diff-1a3d3e2df9dacfb36c9df0d999baf3a817992c8dce1e5b0f5c753b174312f1aeL28-R28): Changed `@ts-ignore` to `@ts-expect-error` for better type checking. …

refactor(bananass): update TypeScript error handling (`@ts-*`) and add `URL_NPM` constant

---

package.json

This pull request includes a small but important change to the `package.json` file. The change updates the Prettier commands to include the `--ignore-unknown` flag, which helps prevent errors when encountering unknown file types.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L55-R58): Updated `fix:prettier` and `lint:prettier` commands to include the `--ignore-unknown` flag.

chore(*): update prettier commands to include `--ignore-unknown` option

---

packages/eslint-config-bananass/src/rules/eslint/eslint-suggestions.js
packages/eslint-config-bananass/src/rules/react/react.js

This pull request includes updates to the ESLint configuration rules in the `packages/eslint-config-bananass` package. The changes focus on modifying rule settings for better code quality and consistency.
* [`packages/eslint-config-bananass/src/rules/eslint/eslint-suggestions.js`](diffhunk://#diff-1f441d9b82dbdd31cd2b0b9d9d6c30b2d66b91dfed4e1f4703da5ef1e295430cL1051-R1051): Changed the `avoidQuotes` option to `false` in the `quote-props` rule to enforce consistent property quoting.
* [`packages/eslint-config-bananass/src/rules/eslint/eslint-suggestions.js`](diffhunk://#diff-1f441d9b82dbdd31cd2b0b9d9d6c30b2d66b91dfed4e1f4703da5ef1e295430cL1226-R1226): Updated the `require-unicode-regexp` rule to `'warn'` with a `{ requireFlag: 'u' }` option to encourage the use of Unicode flag in regular …

fix(eslint-config-bananass)!: update rule configurations for better linting accuracy

---

.github/sync-client.yml
packages/prettier-config-bananass/package.json
packages/prettier-config-bananass/tsconfig.json

This pull request includes several changes to the configuration and build process for the `prettier-config-bananass` package. The most important changes include adding TypeScript support, updating the build script, and modifying the synchronization configuration.
* [`packages/prettier-config-bananass/package.json`](diffhunk://#diff-0fdaf27a6fc3a9c98ce068e2f60dd6fa1d2a82cfc232695581bcae3256c32d76L7-R28): Added TypeScript type definitions and `typesVersions` to the package exports.
* [`packages/prettier-config-bananass/tsconfig.json`](diffhunk://#diff-8f47112bbc5a70fcf4edf6096e3dcd87ebf1fcdde395a04e1a339753a5d84cd6R1-R16): Added a new TypeScript configuration file to generate type declarations and specify compiler options.
* [`packages/prettier-config-bananass/package.json`](diffhunk://#diff …

feat(prettier-config-bananass): add type support

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript/package.json
packages/create-bananass/templates/typescript/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.0` to `v0.1.0-canary.1` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14430009239) for more details.
| Short SHA   | 1c76690       |
| Old Version | `v0.1.0-canary.0`  |
| New Version | `v0.1.0-canary.1`  |
* refactor(bananass)!: refactor, rename and delete unnecessary files by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/155
* feat(eslint-config-bananass)!: remove `eslint-config-bananass-react` and move them to …

chore(release): bump package versions from `v0.1.0-canary.0` to `v0.1.0-canary.1` (`prerelease`)

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript/package.json
packages/create-bananass/templates/typescript/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.1` to `v0.1.0-canary.2` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14446388697) for more details.
| Short SHA   | 9aa0c05       |
| Old Version | `v0.1.0-canary.1`  |
| New Version | `v0.1.0-canary.2`  |
* refactor(prettier-config-bananass)!: migrate to ESM by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/324
* refactor(eslint-config-bananass)!: migrate to ESM by @lumirlumir in …

chore(release): bump package versions from `v0.1.0-canary.1` to `v0.1.0-canary.2` (`prerelease`)

---

lint-staged.config.mjs
package-lock.json
package.json

This pull request includes updates to the linting and formatting configurations to automate code fixes and adds a new development dependency.
* [`lint-staged.config.mjs`](diffhunk://#diff-7de6c7dbbd1b286aac2271abff52aed05b83379c998f2158f357046f9fd06c7dL3-R7): Updated `prettier` and `eslint` commands to automatically fix issues instead of just checking them. Also, added the `--fix` flag to `markdownlint` command.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R56): Added new `fix:markdownlint` script to automatically fix markdown issues.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R65): Added `@types/node` as a development dependency.

chore(*): install `@types/node` and update `lint-staged` configuration

---

packages/eslint-config-bananass/src/index.js
packages/eslint-config-bananass/templates/jsdoc.md

This pull request introduces type definitions and improves code clarity by adding JSDoc annotations and switching to ES module syntax for exports in the `eslint-config-bananass` package.
* Added a `PackageJson` typedef to define the structure of `package.json` files, including `name` and `version` properties. This typedef is used to annotate the `name` and `version` variables. (`packages/eslint-config-bananass/src/index.js`, [packages/eslint-config-bananass/src/index.jsR18-R32](diffhunk://#diff-da6ac4dc852a85b2a5c769cf09235e210f89ee7efbfd4f64929d892bf91a5848R18-R32))
* Replaced `module.exports` with `export default` for ES module syntax and added a JSDoc type annotation (`Linter.RulesRecord`) to the exported object for better type safety. …

fix(eslint-config-bananass): enhance JSDoc template and update types in `index.js`

---

package-lock.json
packages/bananass/package.json
packages/bananass/src/commands/bananass-build/build.js
tests/e2e/bananass-build/cjs.test.js
tests/e2e/bananass-build/fixtures/cjs/bananass/3000.js
tests/e2e/bananass-build/fixtures/mjs/bananass/3000.js
tests/e2e/bananass-build/mjs.test.js

This pull request introduces Babel into the `bananass` package to ensure compatibility with modern ECMAScript features and updates the build process accordingly. It also adds comprehensive end-to-end tests to validate the transpilation of ES2025 features. Key changes are grouped into dependency updates, build process modifications, and test additions.
* Added Babel dependencies (`@babel/core`, `@babel/preset-env`, and `babel-loader`) to `packages/bananass/package.json` to enable transpilation of modern JavaScript features.
* Replaced `esbuild-loader` with `babel-loader` in the `bananass-build` command. Configured Babel to target Node.js 16.13 and use `@babel/preset-env` for transpilation.
* Updated `cjs.test.js` and `mjs.test.js` to include new test cases verifying the correct …

fix(bananass): replace esbuild loader with babel loader for js code bundling

---

packages/bananass/src/babel-plugins/index.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/index.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/transform-array-prototype-to-reversed.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/transform-array-prototype-to-reversed.test.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-sorted/transform-array-prototype-to-sorted.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-sorted/transform-array-prototype-to-sorted.test.js
packages/bananass/src/commands/bananass-build/build.js
tests/e2e/bananass-build/cjs.test.js
tests/e2e/bananass-build/fixtures/cjs/bananass/3002.js
tests/e2e/bananass-build/fixtures/mjs/bananass/3002.js
tests/e2e/bananass-build/mjs.test.js

This pull request introduces a new Babel plugin, `transform-array-prototype-to-reversed`, which transforms calls to `array.prototype.toReversed()` into `array.prototype.slice().reverse()`. It also includes updates to integrate this plugin into the build process, adds unit and end-to-end tests, and refines the existing `transform-array-prototype-to-sorted` plugin.
* **Implementation of the `transform-array-prototype-to-reversed` plugin**: Added a Babel plugin to transform `array.prototype.toReversed()` into `array.prototype.slice().reverse()`. This ensures compatibility with older JavaScript environments. (`packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/transform-array-prototype-to-reversed.js`)
* **Export and integration**: The new plugin is exported from …

feat(bananass): support `Array.prototype.toReversed` transpilation using custom babel plugin

---

packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/transform-array-prototype-to-reversed.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-reversed/transform-array-prototype-to-reversed.test.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-sorted/transform-array-prototype-to-sorted.js
packages/bananass/src/babel-plugins/transform-array-prototype-to-sorted/transform-array-prototype-to-sorted.test.js

This pull request enhances the Babel plugins `transform-array-prototype-to-reversed` and `transform-array-prototype-to-sorted` to support both dot notation (`arr.toReversed()` / `arr.toSorted()`) and bracket notation (`arr["toReversed"]()` / `arr["toSorted"]()`). It also updates the corresponding test files to verify the new functionality.
* [`transform-array-prototype-to-reversed.js`](diffhunk://#diff-b463a2ad23181771ae5aa133821dc0cc5ae733374389abec1f667e32ee36b12cL35-R39): Added support for computed properties (e.g., bracket notation) when transforming `toReversed` calls. Removed the outdated TODO comment about adding computed property support. [[1]](diffhunk://#diff-b463a2ad23181771ae5aa133821dc0cc5ae733374389abec1f667e32ee36b12cL35-R39) …

feat(bananass): add support computed bracket form for `toSorted` and `toReversed`

---

package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript/package.json
packages/create-bananass/templates/typescript/package.json
tests/integration/package-json.test.js
tests/integration/package.json

This pull request introduces several changes to the `npm-bananass` project, focusing on adding integration tests, updating Node.js engine requirements, and improving package exports. Below is a summary of the most important updates:
* Added a new integration test suite (`tests/integration`) to ensure consistency in `engines.node` versions across `package.json` files. This includes a test file (`tests/integration/package-json.test.js`) and a corresponding `package.json` configuration for the test suite. [[1]](diffhunk://#diff-6087f8ce19f5cb0a5122609a76f2f2b16db3cc86c5b4c949032ea9b47943bccbR1-R44) [[2]](diffhunk://#diff-c00d3342bd6ea1035b41a632bc4aa66fb142773d3ad70d34586e29976cd0f884R1-R14)
* Updated the `engines.node` field in various `package.json` files to support Node.js versions …

test(*): create integration tests for package json `engines.node` field

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript/package.json
packages/create-bananass/templates/typescript/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.2` to `v0.1.0-canary.3` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14634205891) for more details.
| Short SHA   | cf78531       |
| Old Version | `v0.1.0-canary.2`  |
| New Version | `v0.1.0-canary.3`  |
* feat(bananass): support `Array.prototype.toSorted` transpilation using custom babel plugin by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/350
* feat(bananass): support `Array.prototype.toReversed` transpilation …

chore(release): bump package versions from `v0.1.0-canary.2` to `v0.1.0-canary.3` (`prerelease`)

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript/package.json
packages/create-bananass/templates/typescript/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.3` to `v0.1.0-canary.4` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14666575875) for more details.
| Short SHA   | 07d7535       |
| Old Version | `v0.1.0-canary.3`  |
| New Version | `v0.1.0-canary.4`  |
* fix(create-bananass): `.gitignore` file is ignored when publish to npm by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/368
* ci(*): create `test-cross-platform.yml` by @lumirlumir in …

chore(release): bump package versions from `v0.1.0-canary.3` to `v0.1.0-canary.4` (`prerelease`)

---

package-lock.json
packages/eslint-config-bananass/package.json

This pull request updates the version of the `eslint-plugin-react-compiler` dependency in the `packages/eslint-config-bananass/package.json` file to a newer release candidate version (`^19.1.0-rc.1`).

chore(deps): bump `eslint-plugin-react-compiler`

---

package-lock.json
packages/create-bananass/package.json
packages/create-bananass/src/cli.js

This pull request introduces a new dependency, `is-interactive`, to enhance the interactivity of the CLI tool and updates the logic in the `cli.js` file to leverage this dependency. Below are the key changes:
* Added `is-interactive` version `^2.0.0` as a new dependency in `packages/create-bananass/package.json`.
* Imported `is-interactive` in `packages/create-bananass/src/cli.js` to check if the terminal session supports interactivity.
* Updated the conditional logic in the CLI flow to ensure prompts are only shown when the terminal is interactive and the `--yes` flag (`cliYes`) is not set.

fix(create-bananass): make cli command to work in a non-interactive environment

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.4` to `v0.1.0-canary.5` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14707186236) for more details.
| Short SHA   | 3c8cc2e       |
| Old Version | `v0.1.0-canary.4`  |
| New Version | `v0.1.0-canary.5`  |
* feat(create-bananass): support ESM and CJS module system templates for JavaScript and TypeScript by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/371
* fix(create-bananass): make cli command to work in a …

chore(release): bump package versions from `v0.1.0-canary.4` to `v0.1.0-canary.5` (`prerelease`)

---

websites/vitepress/ko/learn/q-and-a.md

This pull request updates the Korean Q&A documentation to include answers to common browser-related errors on Linux and WSL environments.
Documentation Updates:
- Added a new question regarding `Error: spawn xdg-mime ENOENT` or `Error: spawn xdg-open ENOENT`, explaining that it's caused by missing `xdg-utils` in Linux or WSL and how to install it.
- Added a new question addressing WSL-specific browser launch issues such as `Wslview is not supported as a default browser`, with a workaround using the `--browser` option in the Banana CLI.
These additions aim to help users troubleshoot common issues encountered when running browser-related commands in Linux and WSL environments.

docs(websites-vitepress): add Linux and WSL browser error Q&A

---

packages/bananass/src/commands/bananass-run/run.js
packages/bananass/src/core/fs/index.js
packages/bananass/src/core/fs/webpack-resolve/index.js
packages/bananass/src/core/fs/webpack-resolve/webpack-resolve.js

This pull request refactors the use of the `enhanced-resolve` library by encapsulating its functionality into a dedicated `webpack-resolve` module. This change improves code organization and reusability across the project. Additionally, a minor update was made to clarify a TypeScript error comment.
* Moved the `enhanced-resolve` logic into a new `webpack-resolve` module located at `packages/bananass/src/core/fs/webpack-resolve/webpack-resolve.js`. The module creates a resolver with `SUPPORTED_SOLUTION_FILE_EXTENSIONS` and exports it for reuse.
* Updated the `fs/index.js` file to re-export the new `webpackResolve` module alongside `findRootDir`.
* Replaced the inline `enhanced-resolve` logic in `bananass-run/run.js` with the imported `webpackResolve` from the new module. This reduces …

refactor(bananass): detach `webpackResolve` logic from `run.js`

---

examples/solutions-bananass-cjs/bananass/31403.js
examples/solutions-bananass-cts/bananass/31403.ts
examples/solutions-bananass-mjs/bananass/31403.js
examples/solutions-bananass-mts/bananass/31403.ts
packages/bananass/src/commands/bananass-run/run.js
packages/bananass/src/commands/bananass-run/test-runner.js

This pull request introduces new solutions for the "bananass" problem in multiple module formats (CommonJS, ESM, TypeScript), along with updates to the `bananass-run` command to improve type safety and test result handling. Below is a summary of the key changes:
* Added solutions for the "bananass" problem in the following formats:
- CommonJS JavaScript (`examples/solutions-bananass-cjs/bananass/31403.js`)
- TypeScript with CommonJS (`examples/solutions-bananass-cts/bananass/31403.ts`)
- ESM JavaScript (`examples/solutions-bananass-mjs/bananass/31403.js`)
- TypeScript with ESM (`examples/solutions-bananass-mts/bananass/31403.ts`)
* Improved type annotations in `run.js` for the `testResults` variable, ensuring it matches the return type of the `testRunner` function …

fix(bananass): run command should be considered a match regardless of whether it ends with whitespace

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.5` to `v0.1.0-canary.6` (`prerelease`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14907692682) for more details.
| Short SHA   | 3df3983       |
| Old Version | `v0.1.0-canary.5`  |
| New Version | `v0.1.0-canary.6`  |
* fix(bananass): run command should be considered a match regardless of whether it ends with whitespace by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/397
* chore(*): cleanup examples and update scripts field of …

chore(release): bump package versions from `v0.1.0-canary.5` to `v0.1.0-canary.6` (`prerelease`)

---

websites/vitepress/.vitepress/config/en.js
websites/vitepress/.vitepress/config/ko.js

This pull request refactors the `items` generation logic in the VitePress configuration files for both English (`en.js`) and Korean (`ko.js`) locales. The changes improve code readability and ensure that items are sorted alphabetically by file name.
* **Introduced `node:path` module**: Added `parse` from `node:path` to both `websites/vitepress/.vitepress/config/en.js` and `websites/vitepress/.vitepress/config/ko.js` to facilitate file name parsing. [[1]](diffhunk://#diff-e8c9834d429fe2a2ab737c4d4792e53b5b37662b8a6ca63da5d0436b5f1231beR12) [[2]](diffhunk://#diff-5f7efba08157e85cfd217cddfc20d73024f20fa0f48b6f230844d9328fb31f57R12)
* **Alphabetical sorting for Baekjoon solutions**:
- Updated the `items` generation logic for Baekjoon solutions in the English config to sort file names …

docs(websites-vitepress): fix the ordering of solution files in sidebar

---

.github/workflows/test-cross-platform.yml
package.json
packages/bananass-utils-console/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
websites/vitepress/ko/get-started/quick-start.md

This pull request updates the supported Node.js versions across the project to include version 24.0.0 and makes minor documentation improvements. The key changes are grouped into updates to Node.js version support and documentation enhancements.
* [`.github/workflows/test-cross-platform.yml`](diffhunk://#diff-290907d9a4bcf13181105b134bd1645da5a3ef27c54f148ad5823e6b77e88426L27-R27): Updated the Node.js version matrix for CI testing to include version `24.0.0`.
* `package.json` and multiple `package.json` files in sub-packages (`packages/bananass-utils-console`, `packages/bananass`, `packages/create-bananass`, and its templates): Updated the `engines.node` field to include support for `^24.0.0`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7-R7) …

chore(*)!: drop support for Node.js 23

---

examples/solutions-bananass-cjs/bananass/30802.js
examples/solutions-bananass-cts/bananass/30802.ts
examples/solutions-bananass-mjs/bananass/30802.js
examples/solutions-bananass-mts/bananass/30802.ts
websites/vitepress/en/solutions/baekjoon/30802.md
websites/vitepress/ko/solutions/baekjoon/30802.md

This PR adds:
- An example input/output case for BOJ Problem 30802 – T-shirt and Pen Distribution
- A Markdown file (30802.md) with a concise explanation including LaTeX-formatted formulas
- The example is added in all supported formats:
- CommonJS (.cjs)
- ES Module (.mjs)
- TypeScript CommonJS (.cts)
- TypeScript ES Module (.mts)
- The explanation is written in both Korean and English documents, using LaTeX for clean math formatting

docs(*): add example for BOJ Problem 30802

---

packages/bananass-utils-console/src/icons/icons.js
packages/bananass/src/commands/bananass-run/run.js

This pull request introduces new icon constants for improved readability and updates the `bananass-run` command to utilize these constants, enhancing code maintainability. Additionally, it includes minor refactoring and cleanup in the `bananass-run` command file.
* Added `bulletIcon` and `boxDrawingsLightHorizontalIcon` constants in `packages/bananass-utils-console/src/icons/icons.js` for reusable symbols (`•` and `─`).
* Updated `bananass-run` command to import and use the new `bulletIcon` and `boxDrawingsLightHorizontalIcon` constants, replacing inline Unicode characters for bullets and horizontal lines. [[1]](diffhunk://#diff-e32949e4dff2549ab48c17b6a98d88eff1f009162d34c041087ba9fdd1480ce2R15-R18) [[2]](diffhunk://#diff-e32949e4dff2549ab48c17b6a98d88eff1f009162d34c041087ba9fdd1480ce2L15 …

refactor(bananass): cleanup `run` command

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0-canary.6` to `v0.1.0` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/14977582819) for more details.
| SEMVER      | `patch`     |
| Short SHA   | fe675c7       |
| Old Version | `v0.1.0-canary.6`  |
| New Version | `v0.1.0`  |
* chore(*)!: drop support for Node.js 23 by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/425
* docs(*): create more examples and solutions by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/418
* docs(websites-vitepress): fix the …

chore(release): bump package versions from `v0.1.0-canary.6` to `v0.1.0` (`patch`)

---

websites/vitepress/.vitepress/config/en.js
websites/vitepress/.vitepress/config/ko.js
websites/vitepress/en/learn/submitting-a-solution-file.md
websites/vitepress/en/learn/submitting-directly-on-the-website.md
websites/vitepress/en/learn/submitting-using-cli-command.md
websites/vitepress/ko/get-started/quick-start.md
websites/vitepress/ko/learn/submitting-a-solution-file.md
websites/vitepress/ko/learn/submitting-directly-on-the-website.md
websites/vitepress/ko/learn/submitting-using-cli-command.md

This pull request consolidates documentation for submitting solution files by merging separate pages into a single unified page and updating references accordingly. The changes simplify the navigation structure and ensure consistency across English and Korean versions of the documentation.
* In both `websites/vitepress/.vitepress/config/en.js` and `websites/vitepress/.vitepress/config/ko.js`, replaced the nested structure for "Submitting a Solution File" with a direct link to the unified page `/submitting-a-solution-file`. [[1]](diffhunk://#diff-e8c9834d429fe2a2ab737c4d4792e53b5b37662b8a6ca63da5d0436b5f1231beL271-R271) [[2]](diffhunk://#diff-5f7efba08157e85cfd217cddfc20d73024f20fa0f48b6f230844d9328fb31f57L271-R271)
* Created a new unified page `submitting-a-solution-file.md` for both …

docs(websites-vitepress): consolidate submitting section

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.0` to `v0.1.1` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/15141914141) for more details.
| SEMVER      | `patch`     |
| Short SHA   | 8801962       |
| Old Version | `v0.1.0`  |
| New Version | `v0.1.1`  |
* chore(*): remove `is-interactive` dependency and update Codecov configuration by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/441
* docs(websites-vitepress): update api documentation by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/450
* …

chore(release): bump package versions from `v0.1.0` to `v0.1.1` (`patch`)

---

packages/bananass/src/cli/bananass-add.js
packages/bananass/src/cli/bananass-bug.js
packages/bananass/src/cli/bananass-build.js
packages/bananass/src/cli/bananass-discussion.js
packages/bananass/src/cli/bananass-home.js
packages/bananass/src/cli/bananass-info.js
packages/bananass/src/cli/bananass-open.js
packages/bananass/src/cli/bananass-repo.js
packages/bananass/src/cli/bananass-run.js
packages/bananass/src/core/cli/groups.js
packages/bananass/src/core/cli/options.js

This pull request introduces several enhancements to the `bananass` CLI by adding grouped options to commands and improving the organization of CLI options. The most significant changes include the creation of reusable option groups, updates to individual commands to use these groups, and minor improvements to the codebase for clarity and maintainability.
* [`packages/bananass/src/core/cli/groups.js`](diffhunk://#diff-e5689e43172bd0a53d671cf2a795cc52b5e44b6f21774a15c63345d9fbaf1653R1-R18): Introduced reusable option groups (`global`, `browser`, `console`, `build`, `info`) to standardize and organize CLI options. These groups are used across multiple commands.
* Updated the following commands to use the new option groups:
- `bug` command: Added `browserGroup` and `consoleGroup` and …

refactor(bananass): streamline command options with new groups for better organization

---

websites/vitepress/ko/get-started/editor-setup.md

This pull request significantly enhances the Korean "Editor Setup" documentation for the Banana Framework by replacing a placeholder with detailed content. It introduces recommendations for setting up and configuring popular code editors, as well as specific guidance for using tools like ESLint and Prettier with VS Code.
* **Introduction and Overview**:
- Replaced placeholder with a detailed introduction to setting up a development environment for the Banana Framework, including benefits of proper editor configuration.
- Added a table of contents (`[[TOC]]`) for better navigation.
* **Editor Recommendations**:
- Provided a list of popular editors (e.g., VS Code, IntelliJ IDEA, Sublime Text, WebStorm, Vim) with descriptions of their features and suitability for JavaScript/TypeScript …

docs(websites-vitepress): complete `editor-setup.md`

---

.github/dependabot.yml
eslint.config.mjs

This pull request includes updates to the Dependabot configuration and a refactor in the ESLint configuration file to improve maintainability and consistency. The most important changes are grouped below:
* Reduced the `open-pull-requests-limit` from 3 to 2 for both the `typescript-eslint` and the scoped dependencies in the `.github/dependabot.yml` file. This helps manage the number of active pull requests more effectively. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L33-R33) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L51-R51)
* Replaced the inline `ignores` configuration with the `globalIgnores` helper function in `eslint.config.mjs`, simplifying the configuration and improving readability.

chore(*): update ESLint config and dependabot

---

websites/vitepress/ko/apis/create-bananass.md
websites/vitepress/ko/learn/other-useful-cli-commands.md
websites/vitepress/ko/learn/writing-bananass-config-file.md

This pull request enhances the Korean documentation for the Banana Framework by adding detailed explanations of CLI commands, their options, and usage examples. It also introduces a new section to clarify the priority of configuration options between CLI commands and `bananass.config.*` files.
* **Expanded CLI Command Descriptions**: Added detailed descriptions, usage examples, and option tables for multiple CLI commands, including `build`, `run`, `open`, `home`, `repo`, and more. These updates make it easier for users to understand how to use each command effectively. [[1]](diffhunk://#diff-91f4adf76df66a2d7ca53d94359d33cc81580d4aaad1940b255c00c63d6711d9R5-R24) [[2]](diffhunk://#diff-91f4adf76df66a2d7ca53d94359d33cc81580d4aaad1940b255c00c63d6711d9L76-R92) …

docs(websites-vitepress): complete `other-useful-cli-commands.md`

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.1` to `v0.1.2` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/15485197325) for more details.
| SEMVER      | `patch`     |
| Short SHA   | 0a7118a       |
| Old Version | `v0.1.1`  |
| New Version | `v0.1.2`  |
* chore(*): update ESLint config and dependabot by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/479
* docs(websites-vitepress): complete `editor-setup.md` by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/475
* docs(websites-vitepress): update …

chore(release): bump package versions from `v0.1.1` to `v0.1.2` (`patch`)

---

.github/sync-client.yml
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass-utils-vitepress/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
scripts/cp.mjs

This pull request introduces a new script (`cp.mjs`) to handle file copying operations and replaces the usage of `shx` with this script across multiple packages. Additionally, it removes the `shx` dependency from the project. Below are the most important changes grouped by theme:
* Added a new script `scripts/cp.mjs` to copy files from source to destination using Node.js's `fs` module. This script replaces the previous reliance on `shx` for file copying.
* Removed the `shx` dependency from `package.json`, as its functionality is now handled by the new script.
* Updated the `build` scripts in multiple `package.json` files to use `node ../../scripts/cp.mjs` instead of `shx cp` for copying `LICENSE.md` and `README.md` files:
- `packages/bananass-utils-console/package.json`
- …

build(*): create `cp.mjs` script for file copying and drop `shx`

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.1.2` to `v0.2.0` (`minor`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/16164614874) for more details.
| SEMVER      | `minor`     |
| Short SHA   | 92a01a0       |
| Old Version | `v0.1.2`  |
| New Version | `v0.2.0`  |
* refactor(bananass)!: rename `secretMode` option to `secret` by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/507
* refactor(*)!: remove `bananass-utils-vitepress` package by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/555
* …

chore(release): bump package versions from `v0.1.2` to `v0.2.0` (`minor`)

---

packages/create-bananass/package.json

This pull request includes a small update to the `build` script in the `packages/create-bananass/package.json` file. The change adds a TypeScript type-checking step (`npx tsc --noEmit`) before running the existing file copy commands.

build(create-bananass): update build script to include TypeScript compilation

---

package-lock.json
package.json
websites/vitepress/.vitepress/theme/style.css
websites/vitepress/package.json

This pull request includes updates to dependencies and styling improvements for the VitePress website. The most important changes involve upgrading packages to newer versions and adding hover effects to a button in the theme's CSS.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L80-R80): Upgraded `textlint-rule-allowed-uris` from version `^1.1.1` to `^2.0.0`.
* [`websites/vitepress/package.json`](diffhunk://#diff-10ef64608fffd18cd9a3d2a3b2adb3361c324abf4a0040a210720ab259c6acd2L16-R16): Upgraded `vitepress` from version `^1.6.3` to `^2.0.0-alpha.9`.
* [`websites/vitepress/.vitepress/theme/style.css`](diffhunk://#diff-616c8254c46be501214dc63263fbbf7649290b5d68d40c83eb94de94f12dedf5R73-R81): Added hover effects to `.DocSearch-Button`, …

chore(*): bump `vitepress` and `textlint-rule-allowed-uris`

---

package-lock.json
packages/bananass/package.json
packages/bananass/src/commands/bananass-build/build.js
packages/bananass/src/core/cli/descriptions.js
websites/vitepress/ko/learn/other-useful-cli-commands.md

This pull request updates the build process for the `bananass` package by removing `esbuild` and refining Babel configurations. The changes primarily focus on transitioning TypeScript transpilation to Babel plugins, improving compatibility with CommonJS modules, and updating documentation and descriptions to reflect these modifications.
* [`packages/bananass/package.json`](diffhunk://#diff-e74f46a7c449d500fc71c84c894fd8e911cf9fe4e54157b741ff6f9cbf357432R96-L105): Removed `esbuild-loader` and replaced `@babel/preset-typescript` with `@babel/plugin-transform-typescript` and `@babel/plugin-transform-modules-commonjs` for more granular control over TypeScript transpilation.
* [`packages/bananass/src/commands/bananass-build/build.js`](diffhunk://#diff-5b3f690c580caae1e82d3789dd6e78d9b694ac24acc …

fix(bananass): drop `esbuild-loader` and reduce package size

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.3.0` to `v0.3.1` (`patch`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/16691723848) for more details.
| SEMVER      | `patch`     |
| Short SHA   | 7c53c0f       |
| Old Version | `v0.3.0`  |
| New Version | `v0.3.1`  |
* fix(bananass-utils-console): internalize `is-interactive` to reduce dependencies by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/630
* fix(bananass): drop `esbuild-loader` and reduce package size by @lumirlumir in …

chore(release): bump package versions from `v0.3.0` to `v0.3.1` (`patch`)

---

package-lock.json
package.json
packages/bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json

This pull request updates various dependencies across multiple `package.json` files to keep the project up to date with the latest versions. The changes primarily focus on updating TypeScript, ESLint, Babel, and related plugins to their latest minor or patch releases.
Dependency updates:
* Updated `typescript` to `^5.9.2` and `@types/node` to `^24.3.0` in the root `package.json` and relevant template packages to ensure compatibility with the latest TypeScript features and Node.js types. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L66-R66) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L81-R81) [[3]](diffhunk://#diff-7d4b13fd6a718a86a0affe334165f4e6441dbea4326c844913cb8316c4ec856eL27-R32) …

chore(*): bump dependencies including `typescript`

---

packages/bananass-utils-console/src/logger/logger.js
packages/bananass-utils-console/src/spinner/spinner.js
packages/bananass-utils-console/src/theme/theme.js

This pull request updates several JSDoc type definitions across the `bananass-utils-console` package to improve type safety and clarity. The main change is making several options explicitly allow `undefined`, which better reflects how these options are used in practice. This helps prevent type errors and makes the documentation more accurate for consumers of these utilities.
Type definition improvements:
* Updated the `Options` typedef in `logger.js` to allow `debug`, `quiet`, and `textPrefix` to be `undefined` as well as their original types.
* Updated the `Options` typedef in `spinner.js` to allow `text`, `color`, `stream`, `isInteractive`, and `spinner` to be `undefined` as well as their original types.
Theme function parameter documentation:
* Updated the JSDoc comments for the …

fix(bananass-utils-console): update type to allow `undefined` in `options`

---

packages/eslint-config-bananass/src/ignores.js

This pull request adds support for ignoring additional configuration files in the ESLint ignore list, specifically files that match wildcard patterns for `jsconfig` and `tsconfig`. This will help ensure that all relevant configuration files are excluded from linting.
Configuration ignore pattern updates:
* Added `**/jsconfig.*.json` and `**/tsconfig.*.json` to the ignore list in `packages/eslint-config-bananass/src/ignores.js`, allowing ESLint to ignore all variants of these config files.

fix(eslint-config-bananass): add additional JSON config ignores for `jsconfig` and `tsconfig`

---

examples/readline/package.json
examples/solutions-bananass-cjs/package.json
examples/solutions-bananass-cts/package.json
examples/solutions-bananass-mjs/package.json
examples/solutions-bananass-mts/package.json
examples/solutions-readline-cjs/package.json
examples/solutions-readline-mjs/package.json
lerna.json
package-lock.json
package.json
packages/bananass-utils-console/package.json
packages/bananass/package.json
packages/create-bananass/package.json
packages/create-bananass/templates/javascript-cjs/package.json
packages/create-bananass/templates/javascript-esm/package.json
packages/create-bananass/templates/typescript-cjs/package.json
packages/create-bananass/templates/typescript-esm/package.json
packages/eslint-config-bananass/package.json
packages/prettier-config-bananass/package.json
tests/e2e/package.json
tests/integration/package.json
websites/eslint-config-bananass/package.json
websites/vitepress/package.json

This PR bumps the package versions from `v0.4.1` to `v0.5.0` (`minor`).
See [Actions](https://github.com/lumirlumir/npm-bananass/actions/runs/18270236564) for more details.
| SEMVER      | `minor`     |
| Short SHA   | a22c44b       |
| Old Version | `v0.4.1`  |
| New Version | `v0.5.0`  |
* fix(bananass)!: remove `bananass/core/structs` export by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/723
* fix(bananass)!: remove `SolutionWithTestcases` type by @lumirlumir in https://github.com/lumirlumir/npm-bananass/pull/724
* feat(*)!: require Node.js …

chore(release): bump package versions from `v0.4.1` to `v0.5.0` (`minor`)

---

packages/eslint-config-bananass/src/files.js

This pull request expands the file matching patterns for configuration files in the ESLint config package to ensure broader coverage for various project setups.
Configuration file pattern updates:
* Added support for matching all variants of `jsconfig` files (e.g., `jsconfig.*.json`) in `files.js`.
* Added support for matching all variants of `tsconfig` files (e.g., `tsconfig.*.json`) in `files.js`.

fix(eslint-config-bananass): add missing wildcard pattern to `jsonc` files
